### ISSUE TITLE
Configure staging and production to run incremental migrations

### ISSUE THREAD

**Issue by colleenskemp** [accessibility-in-action/platform#1039]
Shouldn't take more than 15 minutes, but need to look at Ned's instructions on slack

**Comment by colleenskemp** [comment]
We need to run the initial migrate and seed with production data as seed to both environments.

**Comment by greatislander** [comment]
`php artisan migrate:fresh --seed`

**Comment by greatislander** [comment]
Update: I've done this as we were trying to do some tests on staging and the initial seed data wasn't present.
