### ISSUE TITLE
Add placeholder page with text for features that haven't been implemented yet

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1053]
In order to support translation work, it's necessary to have as many/all copy/text available early. As the strings are pulled from the source, we can temporarily add a template to house the missing copy so that they will be available for translations in the mean time.

**Comment by greatislander** [comment]
@jobara This could be as simple as a single PHP file with an array of localized strings, like:

```php
<?php

return [
  __('Something to translate'),
];
```

My inclination would be to put it in `app/strings.php`.
