### ISSUE TITLE
Password requirements aren't properly validated

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1060]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

When creating a new password it says.

> For your security, please make sure your password has:
>      8 characters or more
>      At least 1 upper case letter
>      At least 1 number
>      At least 1 special character (!@#$%^&*)

However, only the length is validated. A password can be created without an upper case letter, number, and special character. For example 'password'. 

**To Reproduce**
1. Go to "Create an account"
2. Register a new user
3. Use "password" or other non-conforming password that is at least 8 characters long
4. Notice that no error is returned.

**Expected behavior**

Passwords that do not have at least 8 characters, 1 upper case character, 1 number and 1 special character should be rejected and return a validation error.

**Screenshots**

<img width="642" alt="Screen Shot 2022-09-14 at 6 55 27 AM" src="https://user-images.githubusercontent.com/556024/190137015-973c07ca-2318-44fd-b94f-7716d6ccbe9b.png">

**Comment by greatislander** [comment]
@jobara this issue keeps getting filed and I keep closing it— the passwords are not validated on development environments. See: #680

https://github.com/accessibility-exchange/platform/blob/e900833e39105099bc45ab9315f6a19f156a7a11/app/Providers/AuthServiceProvider.php#L68-L74

**Comment by jobara** [comment]
> @jobara this issue keeps getting filed and I keep closing it— the passwords are not validated on development environments. See: #680
> 
> https://github.com/accessibility-exchange/platform/blob/e900833e39105099bc45ab9315f6a19f156a7a11/app/Providers/AuthServiceProvider.php#L68-L74

Is there a reason for this distinction? Is it just to make it easier to type passwords when developing locally? If this distinction needs to be kept it might help to surface something in the UI or elsewhere visible to minimize future filings of this issue.
