### ISSUE TITLE
Minimum number of participants not communicated outside of server validation error

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1064]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

When entering the number of participants for an engagement, the server validation requires a minimum of 10. However, this is not communicated in the UI and the number inputs themselves have `min="1"` specified. 

**To Reproduce**
1. For an organization's project, create an engagement
2. In the "Confirm your participant selection criteria" step, fill in the "Number of participants" inputs with values less than 10.
3. Click "Create engagement"
4. Notice the validation errors for the values being less than 10.

**Expected behavior**

If there is a minimum requirement it should be communicated in the UI. The number inputs should restrict entry to the valid range.

**Screenshots**

<img width="689" alt="Number of participants inputs" src="https://user-images.githubusercontent.com/556024/190208206-766e2509-bf48-4719-bf13-fd05f94943cd.png">

<img width="845" alt="View of DOM showing min=1" src="https://user-images.githubusercontent.com/556024/190208252-7d2ba190-1538-47d5-8dc4-e41b15b2a55f.png">

<img width="718" alt="Validation errors when value less than 10" src="https://user-images.githubusercontent.com/556024/190208271-926c89d6-7edc-4880-bef5-22abc4ac5985.png">

**Comment by cherylhjli** [comment]
The hint text for ideal can be: "This is the ideal number of participants you would like to have for this engagement. The least you can select is 10 participants."

The hint text for minimum can be: "The least number of participants you can have to go forward with your engagement. The least you can select is 10 participants."
