### ISSUE TITLE
Engagement: selecting Community Organization for who you want to engage causes a 500 error

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1066]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

When creating an engagement on the "Who do you want to engage?" step, selecting "Community Organization" results in a 500 error after clicking "Next".

**To Reproduce**
1. Create an Engagement for a Community
2. On the "Who do you want to engage?" step select "Community Organization"
3. Click "Next"
4. See 500 error

**Expected behavior**

Should have continued to the next step in the Engagement creation process.

**Screenshots**

<img width="622" alt="500 error" src="https://user-images.githubusercontent.com/556024/190389480-ed9c0bed-2a54-4854-9dd0-f9acc4c0dda0.png">

**Comment by greatislander** [comment]
@jobara This isn't finished yet— I'm working on it in #984.
