### ISSUE TITLE
Create scheduled task to delete DatabaseNotifications older than 30 days

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1080]
**Is your feature request related to a problem? Please describe.**

We are using Database Notifications via Laravel's notification system to notify users of various events on the platform: https://laravel.com/docs/9.x/notifications#database-notifications

In some circumstances, a user responding to a notification will trigger its deletion. However, other (informational) notifications should be periodically deleted.

**Describe the solution you'd like**

The Laravel scheduler should include a task which deletes any instances of `Illuminate\Notifications\DatabaseNotification` where the `read_at` column >= 30 days ago.

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Not applicable.

**Comment by marvinroman** [comment]
Created new command for use `notifications:remove:old`. Which when passed **n** days, all notifications `read_at` older than **n** days will be deleted.
Created scheduled task that runs the command daily and passes in parameter **30** so notifications that were `read_at` is older than 30 days are deleted.

**Comment by marvinroman** [comment]
Is the solution to remove the notifications like this too brute force?
```php
DB::table('notifications')->where('read_at', '<', DB::raw('DATE_SUB(NOW(), INTERVAL '.$days.' day)'))->delete();
```
This is an alternate that I tested.
```php
 // get formatted date n days ago
  $date = date('Y-m-d', strtotime('-' . $days . ' days'));

  // loop through all users 
  foreach (\App\Models\User::get() as $user) {

      // get all notifications that were read before the date and delete
      foreach ($user->readNotifications->where('read_at', '<', $date) as $notification) {
          $notification->delete();
      }
  }
```
