### ISSUE TITLE
Remove basic auth and add robots.txt to staging.accessibilityexchange.ca

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1083]
**Is your feature request related to a problem? Please describe.**

We'll be opening staging.accessibilityexchange.ca to limited public testing in the next week. So we'll need to make two changes, as follows:

**Describe the solution you'd like**

1. Remove basic authentication.
2. Add a `robots.txt` file with the following contents to prevent indexing:3. 

```
User-agent: *
Disallow: /
```

**Describe alternatives you've considered**

Not applicable.

**Additional context**

Our soft launch is scheduled for Tuesday, September 27 so this needs to be completed by then.

**Comment by marvinroman** [comment]
1. Auth lines removed from values yaml file for staging.
2. `robots.txt` existed with the correct lines, made a small syntax update.
