### ISSUE TITLE
Can't sign out of an account when selecting "Remember me" on the sign in page and keeps getting 419: Page expired error

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#1147]

**Comment by greatislander** [comment]
Confirmed on my local environment and staging.

Specifically, we are seeing: `Illuminate\Session\TokenMismatchException`.

**Comment by greatislander** [comment]
@jobara If you have a chance to take a look at this with me that would be great. I'm quite puzzled.

**Comment by greatislander** [comment]
https://talltips.novate.co.uk/laravel/csrf-and-expired-logout-forms
