### ISSUE TITLE
Users contracted for project loses ability to view project they are contracted for in their dashboard

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#1161]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Removing community connector or Accessibility Consultant role from an individual who is contracted for projects, the individual loses ability to view "Project I'm contracted for" option from their dashboard.

**To Reproduce**
1. Log into an account that is contracted for a project.
2. Update their role to not have either community connector nor accessibility consultant.
3. Go to Dashboard
4. See that the "Project I'm contracted for" option is not present.

**Expected behavior**
User should still be able to see "Project I'm contracted for" option on their dashboard.

**Comment by cherylhjli** [comment]
This should also apply to the tabs on the projects page as well.

**Comment by michelled** [comment]
Completed in the above pull request
