### ISSUE TITLE
Error message could be clearer: "The phone number field is required when contact person vrs is 1."

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1168]
User: community org
Flow: Creating page
Page: Contact information

When the contact person's phone number has not been entered but the VRS checkbox has been checked, it returns the error message "The phone number field is required when contact person vrs is 1." 
This error message could be more clear. Not sure whether you'd want me to write one or whether you would like to do that yourself - please let me know if you'd like me to write one!

**Comment by cherylhjli** [comment]
Realized this is a duplicate.

**Comment by greatislander** [comment]
@cherylhjli duplicate of which issue?
