### ISSUE TITLE
Improve notice to individual who has successfully joined an open call

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1191]
See: https://github.com/accessibility-exchange/platform/pull/1175#issuecomment-1282987111

**Comment by cherylhjli** [comment]
If an individual chooses to not disclose their identity along with their access needs, a few things need to happen:
- the access need still shows up, but anonymously on the FRO's end
- the individual will be prompted to call the service org to get them to help facilitate (maybe a page right after the access needs page with the service org contact info, or a persistent info notification at the top of the engagement page with the contact info, or both)

**Comment by michelled** [comment]
This work is included in https://github.com/accessibility-exchange/platform/issues/1420
