### ISSUE TITLE
Community org cards: Hover state

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1196]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
For community org cards on the manage engagement page:
    - On Firefox, the top band doesn’t change colour to magenta 2 and the stroke doesn’t change to grey 3
    - On chrome, the stroke changes but the top band doesn’t change

**Expected behavior**
Stroke of the card changes to grey 3, 1px.
Top band goes one shade lighter than the inactive state - so magenta 2, in this case.

**Comment by greatislander** [comment]
This is for nested cards (on "Manage engagement" page)
