### ISSUE TITLE
Badges on project cards

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1200]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
The badge currently spans the width of the project card. Have it only fit the content.

**To Reproduce**
Go to any project card

**Screenshots**
<img width="736" alt="Screen Shot 2022-10-19 at 11 05 39 AM" src="https://user-images.githubusercontent.com/9353905/196744813-401e2dd6-9481-4013-b993-5f1fa7c8c9cb.png">

**Comment by greatislander** [comment]
This is fixed in that PR I just talked to you about.
