### ISSUE TITLE
Update to codecov-action to latest version (v3)

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1228]
**Is your feature request related to a problem? Please describe.**

The [codecov-action](https://github.com/codecov/codecov-action) is at v3.1.1 at time of filing this issue. We should try to keep up-to-date with major version changes to get the benefits of the updates.

_**Note:** The underlying [codecov API has updated to v2](https://about.codecov.io/blog/product-update-codecov-api-v2-building-on-feedback-and-improved-repo-onboarding/?utm_medium=email&utm_source=marketo&utm_campaign=october_newsletter&utm_department=marketing), although it isn't clear if we need to upgrade from codecov-action v2 to v3 for this._

**Describe the solution you'd like**

Use the latest version of codecov-action in CI scripts. At time of writing that is v3 (3.1.1).

**Comment by greatislander** [comment]
@jobara It looks like we are using v3 — https://github.com/accessibility-exchange/platform/blob/686fd24f3d0f8a683af8c71d13008d4d3d90d515/.github/workflows/laravel.yml#L82

**Comment by jobara** [comment]
@greatislander thanks, it's my mistake. I meant to file this against [LCIL](https://github.com/fluid-project/lcil) after seeing that it was on V3 here. I've filed it there now https://github.com/fluid-project/lcil/issues/105
