### ISSUE TITLE
Unpublished content should be marked as "Draft" when being viewed.

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1232]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

Whenever content is in an unpublished (publishable) state, it should be marked as "Draft". Currently there is at least one case where this isn't communicated. When an admin views an individual's unpublished page, it appears just as it would when actually published.

**To Reproduce**
1. From an Individual's account, create a public page that is ready to be published, but do not yet publish it.
2. The Individual is able to preview the public page.
3. Switch to an admin user and visit the Individual's page
4. Notice that the page is viewable as though it were published, and misses the "Draft" marking.

**Expected behavior**

All unpolished content should be marked as "Draft"

**Screenshots**

From the Individual's perspective, the preview of the public page indicates that it needs to be published.
<img width="1343" alt="The Individual's view of the public page with a publish button showing." src="https://user-images.githubusercontent.com/556024/198093744-1aa75043-cdda-44ac-be7b-d98da7d5cb0d.png">

From the admin's perspective, there is no indication that the page is still "Draft".
<img width="1509" alt="The admin's view of public page which appears as though published" src="https://user-images.githubusercontent.com/556024/198093906-ebc5fce6-9d19-4596-a7d2-3e8d8a5ef372.png">

**Comment by greatislander** [comment]
See also #675.
