### ISSUE TITLE
Add Sign Language options to Language drop down menu

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1256]
The language drop down provides options for switching between English and French text. There should also be an option(s) to enable/disable the sign language (ASL, LSQ) videos. 

This will allow those without an account to enable the sign language videos feature.

**Comment by jobara** [comment]
@cherylhjli and @greatislander we probably need some design thought on this. Some possible options: 


**Integrating the sign language options directly into the list.** 

- English
- English with ASL
- French
- French with LSQ

**adding a checkbox to the end of the current list** 

- English
- French

- [ ] Enable Sign Language

**Comment by cherylhjli** [comment]
@jobara I prefer the first option, with the Sign Language options being phrased with the Sign Language first - "ASL (with English)", "LSQ (with French)". Based on what I understood from co-design, it would be preferable to recognize ASL and LSQ as distinct primary languages as much as possible!
