### ISSUE TITLE
Project page: Contact can check they need VRS but it doesn't show up on project page

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1266]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I'm filling in the info for the contact person for a project, I can select that they need VRS. However, on the project page there's nowhere that shows up.
<img width="948" alt="Screen Shot 2022-11-02 at 4 37 47 PM" src="https://user-images.githubusercontent.com/9353905/199597801-bfce7ceb-4aa0-4127-902e-9e95ad8ca83a.png">

**To Reproduce**
1. Go to a published project page
2. Under the team contact, enter a phone number and tick off the VRS box.
3. Save and then view the project
5. Go down to the project contact card

**Expected behavior**
Edit the copy to be:
"Please enail [Name] at [email] or phone [phone number] (they require Video Relay Service (VRS) for phone calls)."

**Comment by greatislander** [comment]
@cherylhjli I think this would be a good opportunity to standardize how we display this info. There are currently a lot of variations.

### Engagements

![Image](https://user-images.githubusercontent.com/605361/202333353-8414d51d-ed87-4245-8b4e-6f100132eafe.png)

### Projects

![Image](https://user-images.githubusercontent.com/605361/202333366-fd1fb0a3-a8a3-4733-8373-662e019ad198.png)

### Individuals

![Image](https://user-images.githubusercontent.com/605361/202333638-743bb196-a009-459a-a84b-a3bf0144d41d.png)

### Participants

![Image](https://user-images.githubusercontent.com/605361/202333942-6f0d4b8d-5ed3-42ac-950c-040fc4d508ef.png)

Mainly what I'd like to address is how we display the two contact methods and indicate which is preferred. Perhaps you and @jobara and I could strategize around this a little bit tomorrow.

**Comment by greatislander** [comment]
Contact Wes Chatham
✅ Email: wes@gmail.com
Phone: 905-984-5726 (requires VRS)

Contact Nadine Nicole, Wes Chatham's support personm
✅ Phone: 905-984-5726
Email: nadine@gmail.com

**Comment by cherylhjli** [comment]
project page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=5540%3A110483&t=HJmEteNTFPFV1kvZ-1
Engagement: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2730%3A73293&t=HJmEteNTFPFV1kvZ-1
individual page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A37222&t=HJmEteNTFPFV1kvZ-1
Manage participants: as is
