### ISSUE TITLE
Previewing profile: draft mode notification doesn't appear in other tabs

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1299]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Responding to #1288 and #675 - the warning banner in preview mode is there, but if I click to another tab (ex. projects on FRO page), then back to the "about", the banner disappears.

**To Reproduce**
1. Make an FRO page, make sure account is verified
2. Fill in all required fields and preview the page
3. Click "projects" in the side bar

**Expected behavior**
The notification should be persistent as long as you are in previewing your page.

**Comment by greatislander** [comment]
@cherylhjli That's not a bug. I think there's a misunderstanding here. Let's discuss later.

**Comment by cherylhjli** [comment]
Have banner up top instead of notification, similar to suspended accounts: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A16052&t=HJmEteNTFPFV1kvZ-1

Keep the "edit" buttons throughout the page for a few reasons:
- Ensures "edit" will always take user back to the right section in edit mode
- Reduces need to scroll back up to click edit (especially good for magnification and switch users)
