### ISSUE TITLE
Date picker bugs

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1311]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
- The “day” is pre-populated with "undefined". If I click into it, it doesn’t disappear and I can’t type anything. (However, if I tab into it and it selects the “undefined”, I can edit it). The only way to get rid of it is to click/focus in, and then click out - then it disappears

<img width="497" alt="Screen Shot 2022-11-15 at 3 58 16 PM" src="https://user-images.githubusercontent.com/9353905/202027325-cc01b8e0-8243-4378-b267-f06fbc29830f.png">

**Comment by greatislander** [comment]
I can't reproduce this, @cherylhjli — I'll need more information about where this happens and exactly what you did leading up to when you observed it. I've tried creating a new project and new meeting and not seeing "Undefined" on either.

**Comment by jobara** [comment]
@greatislander while testing #1315 I saw this too. I signed in as the community organization user. I filled out the org page, and approved (as an admin) the org before publishing. I then created a new project and saw the issue mentioned here.

The fieldset has `x-data="dateInput('')"`, is that what is expected?
