### ISSUE TITLE
Akaunting\Money\Currency::setCurrencies(): Argument #1 ($currencies) must be of type array, null given

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1323]
**`TypeError`**

Akaunting\Money\Currency::setCurrencies(): Argument #1 ($currencies) must be of type array, null given, called in /app/vendor/akaunting/laravel-money/src/Provider.php on line 25

:dart: Akaunting\Money\Currency::setCurrencies
:page_facing_up: /app/vendor/akaunting/laravel-money/src/Currency.php

```php
244      }
245  
246*     public static function setCurrencies(array $currencies): void
247      {
248          static::$currencies = $currencies;
```
[Open in Flare](https://flareapp.io/errors/2100478/latest)

Also: https://flareapp.io/errors/2100472, https://flareapp.io/errors/2100486

**Comment by greatislander** [comment]
I believe the issue here is that `deploy:global` runs commands in the following order:

https://github.com/accessibility-exchange/platform/blob/25d925a504e1e0f6fe8a142b0041cb1dac208e04/app/Console/Commands/DeployGlobal.php#L30-L33

However, in some situations before running migrations in may be necessary to clear and cache config (etc). I think the order should be changed so that migrations are run last — `optimize:clear` and `optimize` should take priority as they will cache any needed configuration details from new/updated packages before we try to run migrations.

**Comment by marvinroman** [comment]
Does this better represent what the order should be?
```php
        $this->call('optimize:clear');
        $this->call('event:cache');
        $this->call('optimize');
        $this->call('migrate', ['--step' => true, '--force' => true]);
```

**Comment by greatislander** [comment]
@marvinroman I think that would address the issue, yes!
