### ISSUE TITLE
Users can select ASL/LSQ for page languages but can't add ASL/LSQ content yet

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1332]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Until we support adding user-generated ASL/LSQ content, we should remove these options.

**Comment by michelled** [comment]
<img width="782" alt="Translations" src="https://user-images.githubusercontent.com/562893/223197739-f3553b73-e505-45c2-b46b-85d599bad791.png">
