### ISSUE TITLE
Mobile: Get help bar bugs

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1335]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
- the background of the "get help" bar, when expanded, is missing:
![Screen Shot 2022-11-21 at 12 06 07 PM](https://user-images.githubusercontent.com/9353905/203116639-55bd9f90-c4bc-420f-ad47-a29bb60eceb1.png)

- the focus state is a bit off on one of our tester's devices - iphone 11, safari, using voiceover:
[screenshot here]

**Comment by sepidehshahi** [comment]
![Screen Shot 2022-11-21 at 10 25 31 AM](https://user-images.githubusercontent.com/10619898/203122229-45b4fbf4-beb9-4b67-be45-f523d2ee8d87.png)
