### ISSUE TITLE
Focus and active states on user page side bar nav 

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1350]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
On a user's published page (or when previewing), the side bar links have a focus and active state that are too large:
<img width="110" alt="Screen Shot 2022-11-24 at 1 25 07 PM" src="https://user-images.githubusercontent.com/9353905/203847784-a47a501f-c5e2-425c-a0af-a3e70a4ca053.png">
<img width="76" alt="Screen Shot 2022-11-24 at 1 25 01 PM" src="https://user-images.githubusercontent.com/9353905/203847785-0deab997-575e-43c9-9dcc-b2009b9c790b.png">

**Comment by greatislander** [comment]
@cherylhjli do you have designs for focus states for the sidebar navigation? I think it's inheriting the primary navigation styles which is obviously wrong but wondering if they have documented states.

**Comment by cherylhjli** [comment]
@greatislander can we use the styles we have for regular text links?

**Comment by greatislander** [comment]
@cherylhjli Sure, that works. We might also want to consider the link list pattern? It's what we use for quick links on the user dashboards which is a very similar pattern.
