### ISSUE TITLE
Text to speech bugs

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1377]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Sub-issues**

- [x] #1380
- [x] #1381

**Describe the bug**
- If I play the page, pause, and highlight something before the point where I paused, it resumes reading the page instead of reading the part I highlighted 
- If I play the page, pause, and highlight something AFTER the point where I paused, behaviour is inconsistent for each of my attempts but one of the following happens:
    - I try to play the highlighted passage, It doesn’t play
    - I try to play the highlighted passage, it resumes playing the page instead
- Light theme: 
    - Play page component
        - In the inactive state, the arrow is flipped in direction
        - In the focus state, the arrow has an outline
<img width="175" alt="Screenshot 2022-12-05 at 2 37 40 PM" src="https://user-images.githubusercontent.com/9353905/205728308-3fadd59d-c970-4a7e-9e76-981c37d803fd.png">
    - Play highlight component
        - Active state has diamond shape
<img width="67" alt="Screenshot 2022-12-05 at 2 38 44 PM" src="https://user-images.githubusercontent.com/9353905/205728425-ec1e0b64-8a3c-474f-bff8-bf88dabfce3b.png">
- Dark theme:
    - Play highlight component
        - Hover + active + focused has a diamond shape
<img width="68" alt="Screenshot 2022-12-05 at 2 39 38 PM" src="https://user-images.githubusercontent.com/9353905/205728557-2e2cf7dd-2778-4ce0-9b68-f4f267c8b31e.png">
- Monochromatic theme:
    - Play highlight component
        - Hover + active has diamond shape
<img width="1680" alt="Screenshot 2022-12-05 at 2 40 46 PM" src="https://user-images.githubusercontent.com/9353905/205728630-e1288522-0265-4a63-88dc-1e59bfadc8a5.png">

**Comment by greatislander** [comment]
One note is that Firefox's active state also applies focus styles (if I remember correctly) so that may be causing some of the active display issues.

**Comment by jobara** [comment]
The issue with the arrows on the dark background seem to be related to the fact that css custom properties used in other properties don't pick up the re-declaration of the nested property unless that redefinition is scoped to the same place it was originally defined. To work around this, I'm using less css custom props so they aren't so nested. But they won't be as reusable anymore either. 

See: https://css-tricks.com/the-big-gotcha-with-custom-properties/

**Comment by greatislander** [comment]
@jobara there's an approach I've used for this with "buttons on dark backgrounds" where I have separate custom props for those. Not sure if that would work here.

**Comment by jobara** [comment]
All of the text to speech issues related to this ticket have been addressed.
