### ISSUE TITLE
Update Production deploy for live site

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1385]
Once the production site goes live, the following tasks will need to be addressed to allow access to it:

- [x] #1386
- [x] #1387
- [x] #1388

**Comment by michelled** [comment]
Note that when we go into production for 1.0 we won't be doing these tasks. We are going to keep the site at the current url, behind a password. We will update Robots.txt when we want to be more publicly findable. The site will essentially be in a beta testing phase.

**Comment by jobara** [comment]
All the subtasks have been completed.
