### ISSUE TITLE
Update DNS to point at the live site URL, removing "future"

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1386]
The live URLs should be https://accessibilityexchange.ca and https://www.accessibilityexchange.ca

**Comment by michelled** [comment]
This will not be done for 1.0 - we'll keep the site at the current url until we want to be more publicly findable.

**Comment by jobara** [comment]
This is needed for the friends and family release.

**Comment by jobara** [comment]
Re-openning issue as we still need to update the DNS records themselves. This will be needed when we deploy this to staging.

**Comment by jobara** [comment]
The DNS records (A, AAAA) have been updated to point the domain to the host. The CNAME record for www has been updated to point at accessibilityexchange.ca The addresses will work once the changes from #1939 have been merged into production.
