### ISSUE TITLE
Squash schema with prune

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1389]
For the 1.0 release we plan to run [squash the migrations](https://laravel.com/docs/9.x/migrations#squashing-migrations) so they are dumped to a single file. We also plan to use the `--prune` flag at this time to remove the individual migrations. This is to capture a single state for the 1.0 database structure. We don't expect there to be any DB rollbacks to prior versions. 

For cases where a model's database structure needs to be viewed, the `php artisan show:model {ModelName}` command can be used instead. Relying on the migrations for this is error prone as many changes had been collecting up overtime and it would have required manually parsing the various updates to get the true sense.

**Comment by jobara** [comment]
When performing the schema squash will need to ensure that user is set to `CURRENT_USER`. See #1164
