### ISSUE TITLE
Text to speech bugs pt2

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1398]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I play the page, pause, and highlight something AFTER the point where I paused, it doesn't play.

**To Reproduce**
1. Turn on text to speech
2. Go to any page and hit play the whole page
3. pause and highlight a section of the page that is lower down than where you paused
4. Try to play that highlighted section

**Expected behavior**
It should play the highlighted section.

**Comment by jobara** [comment]
@cherylhjli I tried this out locally and on the dev site this morning using Firefox 107.0.1 on macOS 13.0.1. I wasn't able to reproduce the issue you mentioned above. Could you please let me know if you have a different setup to reproduce the issue. Also if there are specific places on the page I need to pause, and highlight, that might help too.

**Comment by cherylhjli** [comment]
@jobara I can't seem to replicate it today either! perhaps not a problem anymore :)

**Comment by greatislander** [comment]
Closed because neither @cherylhjli nor @jobara could reproduce it.
