### ISSUE TITLE
Enable training user context

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1399]
This will allow users to register independently in order to complete training courses.

Currently disabled for signup here: https://github.com/accessibility-exchange/platform/blob/0bc99859547a5bb84d9ad87083f43f6571cbabe6/app/Providers/FortifyServiceProvider.php#L85

**Comment by jobara** [comment]
@greatislander and @cherylhjli, is this an additional user type? That is, they'd need to register a different account to behave as an Individual user for example? And do they need different e-mail addresses for each of these types of accounts?

**Comment by greatislander** [comment]
@jobara it is an additional user type, yes. However all the other user types can do training. This user type is specifically for people who are signing up _just_ for training, i.e. employees of a regulated organization who don't need access to that regulated organization's account.
