### ISSUE TITLE
Idea: add health check to admin

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1410]
**Is your feature request related to a problem? Please describe.**

It might be beneficial as the site moves towards launch to integrate this: https://github.com/shuvroroy/filament-spatie-laravel-health

**Comment by jobara** [comment]
Laravel 11 comes with a simple up endpoint that can be used to check for health. It doesn't include all of the features that spatie's does, but it might be enough. Note though that the migration from laravel 10 to 11 doesn't include the endpoint configuration, but it can be manually added creating our own route and controller. The controller can call `Event::dispatch(new DiagnosingHealth);` to allow for hooking into the health diagnostics and return a view. The view can be based off of https://github.com/laravel/framework/blob/ca0617aeee70d5e69d7ce7f299af4d1c945cc32c/src/Illuminate/Foundation/resources/health-up.blade.php#L4
