### ISSUE TITLE
Consider switching from spatie/valuestore to spatie/laravel-settings

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1412]
Right now some persistent app settings (contact info in particular) are stored in a JSON valuestore using the Spatie valuestore package. See also: #1409. It might be beneficial to consider switching to a database store using https://github.com/spatie/laravel-settings and [spatie-laravel-settings-plugin](https://filamentphp.com/docs/2.x/spatie-laravel-settings-plugin/getting-started).

**Comment by jobara** [comment]
Will need for #1444
