### ISSUE TITLE
Rework Access Needs Flow

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1420]
* When signing up for an engagement, if the user wants to update their access needs, there is no clear flow from access needs page back to the engagement page:

* During engagement sign up process, on the page for confirming access needs, make the “Update access needs” link larger and bolder or turn it into a button (please check the site for this link, it's not reflected in the designs)

**Comment by cherylhjli** [comment]
Design edits:
Confirm access needs is now two pages, each page having its own task.


https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=6186%3A111433&t=UQ94RjcmmcGxyFuc-1
- This page confirms ALL the user's access needs, regardless of whether they need further consent to attach the name to the access need for the FRO. The task on this page is for the user to confirm that this is their access needs, or edit it.

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=6186%3A110795&t=UQ94RjcmmcGxyFuc-1
- If the user hits "edit", they are taken to this access needs page. The primary button copy below changes to reflect that after they hit it, they go back to the confirm access needs page.

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=6186%3A111650&t=UQ94RjcmmcGxyFuc-1
- After the user confirms their access needs, then they're taken to this page to ask them to give consent for certain access needs to be shown beside their names. If they say yes, they go back to the engagement page with a success notification confirming. If they say no, the same thing happens except the service org also gets a notification to reach out to this user.

**Comment by jobara** [comment]
Wire frames for notification and admin page to managing access needs facilitated by the service. 
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=6653%3A111081&t=0jdSn1jMm2xNGPew-1

**Comment by cherylhjli** [comment]
Access needs that would require us to ask a user to share their identity with an FRO:
- Follow up calls or emails
- Bring my support person
- Everything under the category "For engagement documents"
- Additional needs or concerns - I would like to speak to someone to discuss additional needs or concerns

@jobara

**Comment by jobara** [comment]
Copy for the notification e-mail should be the same as what is displayed in the system notification.

**Comment by cherylhjli** [comment]
@jobara as per our conversation today:
Have a minimum of 5 participants who have signed up before showing any access needs

**Comment by jobara** [comment]
> Access needs that would require us to ask a user to share their identity with an FRO:
> 
> * Follow up calls or emails
> * Bring my support person
> * Everything under the category "For engagement documents"
> * Additional needs or concerns - I would like to speak to someone to discuss additional needs or concerns
> 
> @jobara

Thanks, I looked at the seeder and looks like it's already set up. There were some discrepancies with your list here and the seeder but we talked bout it and the seeder is correct.

https://github.com/accessibility-exchange/platform/blob/8ff1867c10657d529273b8995a683158ca69d3c7/database/seeders/AccessSupportSeeder.php

**Comment by jobara** [comment]
Updates to handle the case where access needs are updated after signing up for an engagement.

- [flow](https://www.figma.com/file/uqZaD5tl3iq9sjGQptRGa6/TAE---flows?node-id=0%3A1&t=IObT98WVyDHFkodk-0)
- [design](https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=7084%3A113228&t=gWbRx9wwYnVqabBL-0)

This was opened as a separate ticket: https://github.com/accessibility-exchange/platform/issues/1578
