### ISSUE TITLE
Browse Project Tweaks

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1422]
* Add a heading for filters in “Browse all projects” page that reads "Filters"
* Move “select none” button to the top of the filters 
* Change the reset filters’ button label from “select none” to clear filters”

**Comment by cherylhjli** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2478%3A65288&t=ycscNGJZ8Jp7Ekp8-1
