### ISSUE TITLE
Getting Started Module

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1444]

**Comment by jobara** [comment]
I believe this is the related design in Figma
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=4%3A137&t=zu7qEewU4FvYnRlL-0

**Comment by michelled** [comment]
This is blocked waiting on a conversation between Keyanna and @cherylhjli

**Comment by michelled** [comment]
> 

@cherylhjli are the design ready to go for this now?

**Comment by jobara** [comment]
Flows for changing roles: https://www.figma.com/file/uqZaD5tl3iq9sjGQptRGa6/TAE---flows?node-id=7-92&t=RrSQmwkr2qbISZbE-0

**Comment by jobara** [comment]
@cherylhjli we'll probably need updated notifications for the users for each type of approval they receive.

**Comment by jobara** [comment]
The workflow to incorporate role changes is very complex. At the moment we are thinking of removing the ability to change roles after sign up. This can be added back in the future when we are able to build out the workflow to allow for changing roles and managing all of the other permissions, restrictions, and etc. needed for this.

**Comment by jobara** [comment]
Collaboration preferences links to a Collaboration Preferences page ([CP](https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1780-48437&t=T8lNltjv9KFQgkYX-0), [AC,CC](https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1784-51670&t=rrJwkMhjBEhsZjJP-0)). I assume if a user has all three roles, the page would be a combination of these items.

**Comment by jobara** [comment]
Need to get the Application links from IRIS. Logan and Keyanna should have them by the end of the week.

**Comment by jobara** [comment]
Links to orientation:

- [Individuals](https://share.hsforms.com/161eyaBsQS-iv1z0TZLwdQwdfpez)
- [Community Organizations](https://share.hsforms.com/1sB6UV4gvQlC_0QxQ3q3z1Adfpez)
- [FROs](https://share.hsforms.com/1gGf9TjhaQ0uaqcnyJfSDlwdfpez)

Links to applications:

- [Community Connector](https://share.hsforms.com/1Pkmwsp2RT9mrvFh2d9iYfQdfpez)
- [Accessibility Consultant](https://share.hsforms.com/16bxWtxLKQmCdjZo4TmJU9wdfpez)
