### ISSUE TITLE
Add privacy policy and terms of service

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1445]

**Comment by jobara** [comment]
Terms of Service:

[mb-tracked -13146560-v8-IRIS - Services Agreement (2).docx](https://github.com/accessibility-exchange/platform/files/10557291/mb-tracked.-13146560-v8-IRIS.-.Services.Agreement.2.docx)

**Comment by michelled** [comment]
The Terms of Service is ready to be incorporated and we should go ahead with that.
The Privacy Policy is waiting on updates from IRIS.

**Comment by jobara** [comment]
Re-opening because the Privacy Policy still needs to be added.

**Comment by michelled** [comment]
Privacy Policy needs to be finalized by IRIS.

**Comment by michelled** [comment]
We should connect both the privacy policy and ToS to Filament so they can be updated as part of this work.

**Comment by jobara** [comment]
Now that https://github.com/chinleung/laravel-multilingual-routes/issues/75 has been fixed, we can take the opportunity to update to the latest release of Laravel-multilingual-routes as we're making changes for the routes related to the ToS and Privacy policy when editing for them is moved into filament.
