### ISSUE TITLE
Engagements cards: "Volunteer" tag shows up for all engagements

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1462]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
"Volunteer" tag shows up for all engagement cards, even though it hasn't been selected.
<img width="900" alt="Screenshot 2023-01-09 at 3 52 50 PM" src="https://user-images.githubusercontent.com/9353905/211689183-a3d3187a-1a1e-4a37-a10b-9cc0ae303ae4.png">

**To Reproduce**
1. Create an engagement
2. Fill out engagement details
3. Go back to manage project page and view the engagement cards

**Expected behavior**
Only show "volunteer" tag if the engagement was made by a community org who selected the volunteer option.

**Comment by jobara** [comment]
@cherylhjli I haven't been able to reproduce this. The Engagements are defaulting to "Paid". 

<img width="866" alt="Screenshot of engagements with Paid badge" src="https://user-images.githubusercontent.com/556024/213448099-641b2bc6-7204-42f0-ab61-becd6abc1b33.png">

Could you please re-test this issue and if you are able to reproduce, include more details on how to reproduce.

**Comment by cherylhjli** [comment]
@jobara I figured it out - if I use the info+regulated-organization account to make an engagement, it's always volunteer. If I make a brand new account that doesn't seem to be an issue!

**Comment by cherylhjli** [comment]
@jobara I spoke too soon - I'm still getting it with the new account I've made. 
The first engagement I made is a focus group with open call, which defaulted to paid.
The second engagement I made is a focus group with CC, which defaulted to volunteer. Every engagement I made after that (survey - open call, survey - CC) defaulted to volunteer.

**Comment by jobara** [comment]
@cherylhjli okay, I think I may have tracked down the issue. For FROs the "Edit engagement details" page is missing the input for selecting if the engagement is "paid" or "volunteer". It is only shown for community orgs. When this page is saved, it sends the request to the server, and the request validation defaults the missing value to `false` which makes it a volunteer engagement. 

So two questions:

1. Should an FRO be able to select if an engagement is paid/volunteer?
2. Should an engagement default to paid or volunteer?

**Comment by cherylhjli** [comment]
@jobara 
1. No, it's intentional that the choice isn't there - an engagement should always be paid if an FRO initiated it. Community orgs, on the other hand, have that choice.
2. Based on your description, it sounds like if FRO's aren't choosing then it needs to default to paid!

**Comment by jobara** [comment]
Based on feedback from @cherylhjli in the [matrix channel](https://matrix.to/#/!cTDzVKxAmJRmfbSdHL:matrix.org/$w1iAPQWfG-p6pL5GBGsF5ChyPFepwSnReO_iT1gxc0o?via=matrix.org), Community Orgs should also default to "paid" but they should be able to change to "volunteer".
