### ISSUE TITLE
404 from accepting engagement invitation from a CC, without making an account first

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1466]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
As a new user, when I created an account to accept an engagement invitation from a CC, I got a 404. However, when I go to my projects page, the project is showing up under projects I am participating in.
 
<img width="1448" alt="Screenshot 2023-01-10 at 3 45 32 PM" src="https://user-images.githubusercontent.com/9353905/211690948-90c2644a-1518-4a3f-98fc-4aff9e975c3a.png">

**To Reproduce**
1. Create an engagement that uses a CC
2. As that CC, invite an individual that doesn't have an account on the website yet with their email 
3. As that individual, create an account using the link in the email. 
4. Go back to email and click accept invitation
5. See error

**Expected behavior**
User should be able to accept invitation without triggering a 404 and have it show up under their projects.

**Comment by jobara** [comment]
@cherylhjli I was only able to reproduce the issue and see a 404 page if I opened the "Accept Invitation" link multiple times. For example:

**Scenario 1:**
1. Clicked "Create Account" in the e-mail
2. Created the account
3. Verified my e-mail
4. Opened "Accept Invitation" from original e-mail
5. Again Opened "Accept Invitation" from original e-mail

or 

**Scenario 2:**
1. Clicked "Create Account" in the e-mail
2. Created the account
3. Before verifying my e-mail address I opened "Accept Invitation" from original e-mail; which leads to a page that says verify e-mail. However, the invitation is accepted with this action.
4. Verified the e-mail address
5. Again Opened "Accept Invitation" from original e-mail

Did you do something similar to the above or something else? I don't think Scenario 1 is a bug. You can only accept the invitation once, that seems correct. The scenario 2 is a bit less clear. I'm not exactly sure why it's happening, but it's kind of like it's fulfilling the acceptance request when the verification hits. I did some logging and it seems that the invitation's accept function is being triggered on step 4 in scenario 2. Note that this doesn't happen if you choose to sign out in step 3, so it might just be something to do with the active session.

@cherylhjli please let me know if one of these scenarios was how you hit the issue and if not, could you clarify the steps you used?

**Comment by jobara** [comment]
I can't quite figure it out, but for whatever reason if you try to accept your invitation before you do the e-mail verification. The e-mail verification step will be immediately followed up with a request to the invitation acceptance. 

That being said, I'm not entirely sure this is a bug. It is kind of convenient, and might be a feature given that when you try to accept the invitation without accepting, it asks you to verify the e-mail first. @cherylhjli let me know your thoughts on this. I think I'll leave it for now, but can look more if you think it needs to be fixed.

**Comment by jobara** [comment]
@cherylhjli okay, I think I've figured it out now. If you hit a page that requires a verified e-mail (this will display a e-mail verification page), verifying the e-mail will attempt to return you to the page that you were trying to visit. Which makes sense as you were blocked on that page. This is exactly the case of what's happening with the invitation acceptance. So when you now very the e-mail, it verifies your e-mail and sends you to the invitation acceptance page you were trying to go to before. Which then accepts the invitation.

This is how it seems to work for all of the pages that require a verified e-mail. So I don't think it is a bug, but please let me know what you think.

**Comment by cherylhjli** [comment]
@jobara it works fine on my end now! Agree, don't think it's a bug and I'm not getting any 400's anymore.

**Comment by jobara** [comment]
It appears that the system is working as intended, and can't reproduce 404 errors by other means.
