### ISSUE TITLE
Remove video and illustration placeholders and put in videos that are ready

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1474]
IRIS has supplied some explanation videos that we should use and they have specified which videos they will not be making.

**Comment by jobara** [comment]
@michelled and @cherylhjli would you be able to add a link to the spreadsheet or copy the info from there into this ticket?

**Comment by michelled** [comment]
https://irisinstituteca.sharepoint.com/:x:/s/TheAccessibilityExchange846/EQ97bN9VvAtHv73SkVrzI1kB9zX1xVUtI1PkYZl-EWEExA?rtime=SmZiyXb52kg

**Comment by jobara** [comment]
Videos

- 0.0.1 - About the Accessibility Exchange
  - en: https://vimeo.com/789855323
  - fr: https://vimeo.com/789772188
  - asl: https://vimeo.com/788810528/73b8c80ad8
  - lsq: https://vimeo.com/789829171
- 0.1.1 - How this works for individuals with disabilities, Deaf people, and supporters
  - en: https://vimeo.com/789854664
  - fr: https://vimeo.com/789823447
  - asl: https://vimeo.com/788815524/4485f30067
  - lsq: https://vimeo.com/789828003
- 0.5.1 - How this works for Community Organizations
  - en: https://vimeo.com/789854538
  - fr: https://vimeo.com/789771460
  - asl: https://vimeo.com/788818374/779a5e9913
  - lsq: https://vimeo.com/789827141
- 0.7.1 - How this works for Federally Regulated Organizations
  - en: https://vimeo.com/789854286
  - fr: https://vimeo.com/789770856
  - asl: https://vimeo.com/788820695/f357173576
  - lsq: https://vimeo.com/789826246
