### ISSUE TITLE
Drop down in internet explorer edge contrast issue

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#1477]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Preferred contact method - drop down in internet explorer edge - the text is white on white background

**To Reproduce**
1. Go to edit public page in Internet Explorer edge on Windows machine
2. Change the theme of the browser to use dark mode
3. Skip to the step "Communication and consultation preferences"
4. Click on Preferred contact method drop down menu

**Expected behavior**
Preferred contact method options should have enough contrast with its background

**Details**
- Operating system: Windows
- Browser: Internet Explorer Edge

**Comment by jobara** [comment]
I did some quick tests using browser stack, but only had a 1 minute to test. It appears this is an issue in Chrome as well, and is likely related to implementation of the underlying chromium that both are based on. We likely just need to apply styling to foreground and background colours of the options portion. See https://blogs.windows.com/msedgedev/2022/05/05/styling-select-elements-for-real/ for more info.
