### ISSUE TITLE
other_disability_connection not persisting

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1478]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

When specifying "Something else" as the Disability Type you can connect to, it is not properly persisted. After the page is saved this value is not restored and is blank again. It did not appear to be stored in the database either.

**To Reproduce**
1. Login as an Individual User
2. Ensure that the "Community Connector" role is enabled
3. Edit your public page
4. Go to the "Groups you can connect to" step
5. Under "Can you connect to people with disabilities and Deaf people, their supporters, or both?" check "People with disabilities and/or Deaf people"
6. Under "Please select the disability and/or Deaf groups that you can connect to." select "Only people with specific disabilities and/or Deaf people"
7. Under "Please select the specific disability and/or Deaf groups that you can connect to." check "Something else"
8. In "Disability type" type in some text
9. Fill in any remaining required fields
10. Click "Save"
11. Notice when the page reloads that "Something else" isn't checked. Checking it again shows the "Disability Type" field empty. 

**Expected behavior**

The data should be persisted and retrieved properly.

**Screenshots**

<img width="863" alt="Screenshot of the Something Else option" src="https://user-images.githubusercontent.com/556024/213306513-b05b1541-fe21-4f9f-a713-ce649858c653.png">

**Comment by michelled** [comment]
Michael and Logan think we can remove the 'something else' and the text box but are going to confirm with Doris.
