### ISSUE TITLE
Home page: Vimeo preview

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1495]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
The vimeo preview on the home - FRO page (https://tae-dev.inclusivedesign.ca/en/about/for-regulated-organizations) looks like UI. This can be confusing for people who may mistake the video preview as actual UI that can be interacted with.

**Expected behavior**
The preview is set to the TAE logo, as it is for the other videos like on this page: https://tae-dev.inclusivedesign.ca/en/about/for-individuals

**Screenshots**
<img width="1387" alt="Screenshot 2023-01-25 at 9 55 50 AM" src="https://user-images.githubusercontent.com/9353905/214657336-44feb381-9b63-459c-bf10-a93c1ebc9845.png">

**Comment by jobara** [comment]
Will need to be updated in Vimeo.

**Comment by jobara** [comment]
@cherylhjli I updated the thumbnails in Vimeo. They should all be using the TAE logo the plays at the beginning of the video.
