### ISSUE TITLE
Update to Laravel 10

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1520]
**Is your feature request related to a problem? Please describe.**

Laravel 10 will be released on Feb 7, 2023 and will have security fixes till Feb 4, 2025.

https://laravel.com/docs/9.x/releases#support-policy

**Comment by michelled** [comment]
We might want to try https://laravelshift.com instead of doing the upgrade ourselves.

**Comment by jobara** [comment]
[Upgrade guide](https://laravel.com/docs/10.x/upgrade)

Consider using a service like [Laravel shift](https://laravelshift.com)

**Comment by jobara** [comment]
Duplicated by #1906
