### ISSUE TITLE
Clicking on uncompleted engagement page throws an error

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#1534]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
While adding an engagement to a project, not completing the creation steps and going back to the project manage page then clicking the uncompleted engagement page throws an error. The uncompleted engagement page also shows up on Projects page under In progress project, which doesn't seem right.

**To Reproduce**
1. Create an engagement 
2. Don't complete it and go back to the project manage page
3. Click on the engagement that is not completed

**Expected behavior**
Should see a page to edit the engagement

**Comment by jobara** [comment]
I was thinking about the Projects page, but I think it does still make sense to show them there. They should link to the appropriate spot but the In Progress is about the Project I believe and it's a quick way to get access to update the engagements.
