### ISSUE TITLE
Update the languages icon to clarify meaning

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1542]
In user testing, the compound icon was very confusing and difficult to understand.

**Comment by jobara** [comment]
New icon design in Figma: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1155-10218&t=BCO4xxOfSTtmLBAX-0

**Comment by jobara** [comment]
The initial suggestion was to only show the sign language portion (signing hands) with the text "languages". However, in the mobile layout the text is removed and only the icon is shown. For this reason we've kept a compound icon but changed the design.
