### ISSUE TITLE
Add intro videos in the sign up process

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1580]
Currently when signing up a new user, there is a page which is empty and says 'intro video'.

**Comment by michelled** [comment]
IRIS needs to provide links to the appropriate videos that have been uploaded to Vimeo.

**Comment by michelled** [comment]
The videos need to be made after the Getting Started Module is complete

**Comment by lochurchill** [comment]
Video links! 

Hey @jobara , updated as of 10:42am ET, 3 October 2023.

English: 

- How this works for Individuals
https://vimeo.com/850314990/05587fe4df?share=copy

- How this works for Community Organizations
https://vimeo.com/850315035/87b6129a8b?share=copy

- How this works for Federally Regulated Organizations
https://vimeo.com/850315068/bc26c699cb?share=copy


ASL:

How this works for Individuals with disabilities, Deaf people & supporters ASL 20230620
https://vimeo.com/850314990/05587fe4df?share=copy

How this works for Community Org ASL 20230620
https://vimeo.com/850315035/87b6129a8b?share=copy

How this works for FRO's ASL 20230620
https://vimeo.com/850315068/bc26c699cb?share=copy

French:

How this works for individuals with disabilities, Deaf people, and supporters French with CC 20230620
https://vimeo.com/850319076/4d973fc4ee?share=copy

How this works for Community Organizations French with CC 20230620
https://vimeo.com/850319102/c118d69046?share=copy

How this works for Federally Regulated Organizations French with CC 20230620
https://vimeo.com/850319118/fd87b58ddc?share=copy

LSQ:

How this works for Individuals with disabilities, Deaf people & supporters LSQ 20230620
https://vimeo.com/850322469/cd5616567a?share=copy

How this works for Community Org LSQ 20230620
https://vimeo.com/850322511/2aad27699a?share=copy

How this works for FRO's LSQ 20230620
https://vimeo.com/850322540/3ee66a159c?share=copy
