### ISSUE TITLE
'Correct answer' text on quiz results page isn't themed

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1590]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

After completing a quiz successfully, you are shown a summary of the questions and the correct answers. However, the 'Correct answer' text is not themed and is hard to read in some of the contrast themes.

**To Reproduce**
1. Sign in
2. Pick one of the contrast themes (i.e not the dark, light or system themes)
3. Go to "Resources and Training" from the top navigation
4. Open a course from the "Featured training" section
5. Complete the course and take the quiz (if using the sample quiz the last two options must be selected for each questions).
6. On the summary page after completing the quiz successfully notice that the "Correct answer" text isn't themed
7. Change themes to see how it looks in each one.

**Expected behavior**

The "Correct answer" text should follow the contrast theme

**Screenshots**

<img width="392" alt="Screenshot of the 'Correct answer' text in a greenish colour while the theme is set to 'light grey on grey'" src="https://user-images.githubusercontent.com/556024/225625629-04960d62-99f7-43b7-9319-cc11ecca368b.png">

**Comment by jobara** [comment]
It seems that the [`correct-answer`](https://github.com/accessibility-exchange/platform/blob/6f25e50042369a9243c9bdd553163e862ab1fea8/resources/css/components/_quiz.css#L1-L3) and [`wrong-answer`](https://github.com/accessibility-exchange/platform/blob/6f25e50042369a9243c9bdd553163e862ab1fea8/resources/css/components/_quiz.css#L9-L11) classes are missing the `var(--fg)` as the first colour option. However, I'm wondering if it is sufficient to have them the same colour or if we need to do more to distinguish this from the rest of the text. @cherylhjli do you have any thoughts or suggestions?

**Comment by cherylhjli** [comment]
@jobara It's sufficient to have the text as the same colour, which can just be the body colour - I think the icon of checkmark or x is sufficient enough to indicate whether it's right or wrong, in addition to the copy itself.
