### ISSUE TITLE
Class "Spatie\SqlCommenter\SqlCommenterServiceProvider" not found

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1596]
**`Error`**

Class "Spatie\SqlCommenter\SqlCommenterServiceProvider" not found

:dart: Illuminate\Foundation\Application::resolveProvider
:page_facing_up: /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php

```php
748      public function resolveProvider($provider)
749      {
750*         return new $provider($this);
751      }
752  
```
[Open in Flare](https://flareapp.io/errors/3468651/latest)

**Comment by jobara** [comment]
This is related to a package, [spatie/laravel-sql-commenter](https://github.com/spatie/laravel-sql-commenter), that was [removed](https://github.com/accessibility-exchange/platform/commit/6f25e50042369a9243c9bdd553163e862ab1fea8) in the [1.0.0-alpha.10 release](https://github.com/accessibility-exchange/platform/releases/tag/v1.0.0-alpha.10).

**Comment by jobara** [comment]
This is a similar issue, although in our case I don't believe we are overriding the `APP_PACKAGES_CACHE`. https://laracasts.com/discuss/channels/laravel/uninstalled-package-but-get-serviceprovider-error-on-optimize

**Comment by marvinroman** [comment]
I couldn't duplicate the issue either on my local development and **composer.json** did start with `spatie/laravel-sql-commenter` and was removed in the upgrade.
 
Not being able to duplicate I still recommend we change **app/Console/Commands/DeployGlobal.php** to run the following commands:

```php
        $this->call('clear-compiled');
        $this->call('optimize:clear');
        $this->call('icons:clear');
        $this->call('icons:cache');
        $this->call('view:cache');
        $this->call('google-fonts:fetch');
        $this->call('optimize');
        $this->call('migrate', ['--step' => true, '--force' => true]);
```

This will flush the compiled files first, before attempting to clear the caches.

I have also removed the unnecessary cache clearing and creation that are already done by the `optimize` commands. Be careful with altering the order. In different orders I got errors, like putting `icon:cache` after `optimize`.

**Comment by marvinroman** [comment]
I did go ahead and put through some small fixes for the local development environment as well as put instructions in [README.md](https://github.com/accessibility-exchange/platform/blob/dev/README.md). 
We can keep it on it's own branch if you want and you can just merge in the branch you want to test. The current branch is **feat/create-local-dev-environment-that-mirrors-kube**.

**Comment by jobara** [comment]
@marvinroman I agree with removing the duplicate cache related commands. That being said, the `clear-compile` command is included in `optimize:clear`. I understand you are trying to run it before clearing the other caches but I would still think that not to be necessary.

So I tested something else out locally. I went back to e2e918a which is just before we removed the sql commenter package. I ran composer install from this and saved the bootstrap directory somewhere else. I then brought the repo back up to the latest dev revision, which is currently the same as the 1.0.0-alpha.10 tag. I ran composer install again. At this point everything is working, including the bootstrap directory updated with the correct caches. I then manually replaced the packages.php and services.php files in the bootstrap/cache directory with those that I had saved earlier. Now running `php artisan optimize:clear`, `php artisan clear-compiled` and `php artisan route:cache` all return the error.

```log
Class "Spatie\SqlCommenter\SqlCommenterServiceProvider" not found

  at vendor/laravel/framework/src/Illuminate/Foundation/Application.php:750
    746▕      * @return \Illuminate\Support\ServiceProvider
    747▕      */
    748▕     public function resolveProvider($provider)
    749▕     {
  ➜ 750▕         return new $provider($this);
    751▕     }
    752▕ 
    753▕     /**
    754▕      * Mark the given provider as registered.

      +7 vendor frames 
  8   artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
``` 

Perhaps you could see if you could reproduce this behaviour. If so, I believe that would mean that the proposed change you suggested for adding `clear-compile` would still trigger the issue. This would also appear to indicate that either something is wrong with the bootstrap cache. Potentially one or more of the following:

- [`composer install` in the docker container](https://github.com/accessibility-exchange/platform/blob/69ed6653fd3f7c75481167eb7f9e1a4c3fff28fd/.deploy/accessibility-app/Dockerfile#L60) isn't updating the bootstrap cache
- The new cache files are not being [copied](https://github.com/accessibility-exchange/platform/blob/69ed6653fd3f7c75481167eb7f9e1a4c3fff28fd/.deploy/accessibility-app/entrypoint.sh#L15-L21) over to the permanent cache properly
  - Are they going to the correct directory?
  - Is there a timing issue with when they are being accessed?
  - Does the mount point exist yet? Could we be doing the rsync with the local filesystem and then accessing the mounted directory when running our artisan commands because the mount happens later. 
- Somehow the old cache is being restored or copied back
- something else

**Comment by marvinroman** [comment]
Thanks for reproducing.

I was able to reproduce in the same way as you. 
Here is what I think is happening. 
`composer install` produces 2 cache files within `boostrap/cache`. `services.php` & `packages.php`.

I wasn't able to confirm, but I am assuming that there are references in other cached files because those 2 files should be updated with the following command within entrypoint:
`rsync -a -/app/bootstrap/cache/ $CACHE_PATH`

The fix is simple. We add a `--del` flag to the `rsync` command to make sure that cached files not in the container are removed.
`rsync -a --del -/app/bootstrap/cache/ $CACHE_PATH`

Make sure to do this on **ONLY** the **/app/bootstrap/cache/** line we don't want to do on the **/app/storage/** otherwise we would remove items from permanent storage.

**Comment by marvinroman** [comment]
The file that was causing the issue was `config.php`.
```php
  'sql-commenter' => 
  array (
    'enabled' => true,
    'commenters' => 
    array (
      'Spatie\\SqlCommenter\\Commenters\\ControllerCommenter' => 
      array (
        'includeNamespace' => false,
      ),
      0 => 'Spatie\\SqlCommenter\\Commenters\\RouteCommenter',
      'Spatie\\SqlCommenter\\Commenters\\JobCommenter' => 
      array (
        'includeNamespace' => false,
      ),
      'Spatie\\SqlCommenter\\Commenters\\FileCommenter' => 
      array (
        'backtraceLimit' => 20,
      ),
      1 => 'Spatie\\SqlCommenter\\Commenters\\CurrentUserCommenter',
    ),
    'commenter_class' => 'Spatie\\SqlCommenter\\SqlCommenter',
  ),
```

**Comment by jobara** [comment]
@marvinroman If I'm following correctly, you're saying the issue is that `deploy:global` creates all the caches but the `composer install` run in the container only creates the `services.php` and `packages.php`. When we do the rsync it leaves behind the old caches, including `config.php`. So the caches are sort of out of sync when we run `deploy:global` in our current deploy.

I did try to reproduce this locally, by going back to e2e918aed13b680874f31d0093a12e27c2fb23e1, running `composer install` and `php artisan deploy:global`, then copying the bootstrap directory somewhere else. I then went back to the head of dev, cleared all the caches and re-ran `composer install`. At this point, I copied over the files from my saved bootstrap directory, except for the `services.php` and `packages.php` files. I used the new instances of these to try to replicate the situation I outlined above. However, I did not run into any errors running any of the artisan commands this time. Am I missing a step or doing something wrong?

Also I'm wondering why the cache needs to live on a shared drive instead of just staying in the containers. I'd imagine there may be an issue with the previous container still running trying to access the cache while the new container is spinning up and updating to a new cache that may contain new config and etc.

**Comment by marvinroman** [comment]
I wasn't able to reproduce the error, but I also had trouble reproducing the error this time by replacing `services.php` and `packages.php` in addition to `config.php`. What could have also happened is what happened previously in that cache was created from old containers before they are killed.

I don't have a good reason to store cache in shared/permanent storage. This should also mitigate the need to put the site into maintenance mode. Would you like me to do a PR for this?

**Comment by jobara** [comment]
> I don't have a good reason to store cache in shared/permanent storage. This should also mitigate the need to put the site into maintenance mode. Would you like me to do a PR for this?

Yes, please. Thanks @marvinroman
