### ISSUE TITLE
Add a popup on first load of the site that draws attention to ASL/LSQ support

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1604]

**Comment by jobara** [comment]
Figma Designs: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=7271-114883&t=Ch1STQS84n0Vq8KK-11

There are both desktop and mobile version.

This should show up the "first" time you visit the page, so we'll need to remember that it's been seen, and it should be available on any of the sites pages. It'll likely be implemented as a modal dialog.

**Comment by jobara** [comment]
Updated translations from Samuel:

```
Welcome to the Accessibility Exchange: Bienvenue sur le Connecteur pour l'accessibilité
You can always change this by selecting the language menu.: Vous pouvez toujours changer de langue en utilisant le menu de langue
```

**Comment by jobara** [comment]
As per conversation with @cherylhjli don't show language confirmation popup on 404 and other error pages. If possible also hide the sign in menu that doesn't work properly there.

**Comment by jobara** [comment]
Video for modal dialog:
https://drive.google.com/drive/folders/12r9VvK_vQoHwEZ_WnTyJqKr3p_hoXNpk?usp=sharing

Vimeo links:

- [Desktop](https://vimeo.com/814610786)
- [Mobile](https://vimeo.com/814610773)
