### ISSUE TITLE
Add a cookie consent/information dialog/notice

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1617]
**Is your feature request related to a problem? Please describe.**

We should indicate to users that we use cookies on the site. 

**Describe the solution you'd like**

Can use [spatie/laravel-cookie-consent](https://github.com/spatie/laravel-cookie-consent) to add the feature, but will likely need designs to match the site look and feel.

**Describe alternatives you've considered**

Implement our own solution, similar to the mechanism used by #1604 to show the language confirmation.

**Additional context**

Will need to assess the accessibility of spatie/laravel-cookie-consent.

**Comment by cherylhjli** [comment]
Design: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=7473%3A118646&t=Vg6IkRBfkXDN2uQY-1
