### ISSUE TITLE
Populate the CHHA course

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#1630]
We should now have all of the content for the CHHA course from Logan. We should replace the 'sample course' with this content.

**Comment by jobara** [comment]
Videos:

- [Q1](https://vimeo.com/814604569)
- [Q1_MC](https://vimeo.com/814604506)
- [Q1_Answer](https://vimeo.com/814604412)
- [Q2](https://vimeo.com/814604625)
- [Q2_MC](https://vimeo.com/814604600)
- [Q2_Answer](https://vimeo.com/814604584)
- [Q3](https://vimeo.com/814604754)
- [Q3_MC](https://vimeo.com/814604684)
- [Q3_Answer](https://vimeo.com/814604654)
- [Q4](https://vimeo.com/814604883)
- [Q4_Answer](https://vimeo.com/814604783)
- [Q5](https://vimeo.com/814604990)
- [Q5_MC](https://vimeo.com/814604939)
- [Q5_Answer](https://vimeo.com/814604912)
- [Q6](https://vimeo.com/814605179)
- [Q6_MC](https://vimeo.com/814605156)
- [Q6_Answer](https://vimeo.com/814605038)

**Comment by michelled** [comment]
We don't yet have the actual webinars - Doris is working on getting them.

**Comment by jobara** [comment]
Webinar Videos:

- Build Environment
  - [Built Environment](https://vimeo.com/824820321?share=copy)
  - [Built Environment FRE](https://vimeo.com/824831128?share=copy)
- Communication in the workplace
  - [Communication in the workplace English ASL](https://vimeo.com/824862933?share=copy)
  - [Communication in the workplace French LSQ](https://vimeo.com/824871878?share=copy)
  - [Communication in the workplace snippet](https://vimeo.com/824886825?share=copy)
  - [Communication in the workplace snippet French](https://vimeo.com/824871878?share=copy)
  - [Workplace communication webinar](https://vimeo.com/824886825?share=copy)
  - [Workplace communication webinar French](https://vimeo.com/824884050?share=copy)
- Customer service
  - [Customer service](https://vimeo.com/825100128?share=copy)
  - [Customer service French](https://vimeo.com/825103452?share=copy)
  - [Customer service snippet French](https://vimeo.com/825105831?share=copy)
- Overview of communication
  - [Overview of communication](https://vimeo.com/824854573?share=copy)
  - [Overview of communication English ASL](https://vimeo.com/824856580?share=copy)
  - [Overview of communication French](https://vimeo.com/824849288?share=copy)
  - [Overview of communication snippet French LSQ](https://vimeo.com/824851477?share=copy)

**Comment by jobara** [comment]
Additional non video resources:

[May 2023 - Additional Non-Video CHHA Resources.zip](https://github.com/accessibility-exchange/platform/files/11441074/May.2023.-.Additional.Non-Video.CHHA.Resources.zip)

**Comment by jobara** [comment]
@chosww I've added links to the webinar videos above, and there are also some non video resources that they've shared with us too.

**Comment by jobara** [comment]
Text content for the course:

[CHHA Resources for TAE 2.zip](https://github.com/accessibility-exchange/platform/files/12018306/CHHA.Resources.for.TAE.2.zip)

**Comment by jobara** [comment]
Things that current course/training don't support but are required:

- Multiple Introduction videos and text
- Localize author (in particular for organization names)
- Signed language videos for quizzes and other courses content
- Different formats of questions/answers

**Comment by jobara** [comment]
In the content for the course it mentions the following:

> For the first video introduction
Welcome to Disability Connect, linking communication to transportation. In this introduction video, you will learn and meet Canadians who share the importance of understanding the various communication needs of individuals with communication disabilities and accessing services in the transportation sector.

>Second video description
Accessible communication is essential to ensure equitable access to people with diverse communication needs. This video provides an overview of the following areas, customer service, built environment, workplace and use of technology.

However we don't have videos for these. We only have videos for the 4 webinars and ASL videos related to the quiz. (See previous comments for links)
