### ISSUE TITLE
Individual public page: Community connector

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1634]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
I made an error and suggested we remove the heading above the body text that says a community connector can connect with any disability or Deaf group - now that I see it in context it seems really out of place. Could we have the heading of "Groups in the disability and Deaf community", with body text being "Any group"?

**To Reproduce**
1. Log in as a user with a CC role
2. Go to edit public page
3. Select the option that says the user can connect with any disability or Deaf group
4. Save or publish
5. Go view the page and see bug

**Comment by jobara** [comment]
@cherylhjli do you want "Any Group" to just be body text or a tag. Wondering how this will look with "Supporters" also appearing as mentioned in #1635.

**Comment by cherylhjli** [comment]
It should appear as a tag to be consistent with the supporter tag!
