### ISSUE TITLE
"Supporter" not showing up on the public page even when selected

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1635]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Even when I select "supporter" as a group I can connect to on the edit public page, it doesn't show up on the public page itself.

<img width="714" alt="Screenshot 2023-04-03 at 3 53 33 PM" src="https://user-images.githubusercontent.com/9353905/229644104-f47b01fb-0f40-4c6e-9153-8672e240a368.png">
<img width="605" alt="Screenshot 2023-04-03 at 3 53 19 PM" src="https://user-images.githubusercontent.com/9353905/229644107-862a5cca-2727-4f6e-a6e6-5823898fd53b.png">

**Expected behavior**
If someone selects both "people with disabilities and/or Deaf people" and "Supporters", have them both show up as a tag on the public page

**Comment by jobara** [comment]
@cherylhjli where should the "Supporters" tag show up?

**Comment by cherylhjli** [comment]
Can it appear like this? https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1540%3A36401&t=xbkMOEvGLxXJZ2Ot-1
