### ISSUE TITLE
"Other" access needs not showing up when confirming access needs for engagement

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1638]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
As a CP when I sign up for an open call, and if I have an access need that I checked "other" and added an access need in the input box below, it doesn't show up under "confirm access needs" in the process of signing up for an open call engagement.

**To Reproduce**
1. Sign in as a CP
2. Go to access needs, check off "other" and input some text into the input field
3. Sign up for an open call engagement
4. When you get to the confirm access needs page, see that the "other" access need + text entered isn't showing up

**Expected behavior**
For the access need to show up as "Other - [text input here]".

**Comment by jobara** [comment]
@cherylhjli, to confirm, these added access needs are treated as non-anonymisable?

**Comment by cherylhjli** [comment]
yes that makes sense! since we don't know what they'd put in there.
