### ISSUE TITLE
Language modal dialog: Spacing for text

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1653]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
Currently there's more space between  "You can always change this by selecting the language menu." and "Vous pouvez toujours changer de langue en utilisant le menu de langue." than the latter and the video. It makes it look like only the latter is connected to the video and the former is just floating there.

**Expected behavior**
Reduce the spacing between the "You can always change this by selecting the language menu." and "Vous pouvez toujours changer de langue en utilisant le menu de langue." so it looks connected to each other.

**Comment by jobara** [comment]
Will fix along with changes for #1654
