### ISSUE TITLE
Move Dev deploy to CoLab hosted infrastructure

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1687]
Currently the IDRC is hosting the dev deploy at https://tae-dev.inclusivedesign.ca. However, it would be better to have the dev deploy on the same infrastructure as the [staging](https://staging.accessibilityexchange.ca) and [production](https://future.accessibilityexchange.ca) sites so that we can have a development deployment that is more closely aligned with what will be deployed to production.

As such, we should start hosting the dev deploy alongside staging and production deploys.

**Comment by jobara** [comment]
CoLab is now hosting the dev site at https://dev.accessibilityexchange.ca. We still need to remove the GitHub based dev deploy configuration that was used for the old dev site.

**Comment by jobara** [comment]
@gtirloni now that we have a dev instance deployed by CoLab we can shut down the one that the IDRC was hosting. Would you be able to look into that, and also removing the the GitHub action and other configuration for it from the repo?

**Comment by gtirloni** [comment]
@jobara Yes, I'll fix that this week. Thanks for the heads up.
