### ISSUE TITLE
Misaligned heading area and main area

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1688]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
On the public pages for any users and projects, the heading area (where the name is) and the main area (where the secondary links area and the main content is) don't line up on the left hand side.
As seen in these pages:
    - https://staging.accessibilityexchange.ca/en/regulated-organizations/ircc
    - https://staging.accessibilityexchange.ca/en/individuals/cheryl
    - https://staging.accessibilityexchange.ca/en/organizations/idrc
    - https://staging.accessibilityexchange.ca/en/projects/2

**Expected behavior**
For these two areas, including the strings around translation and the divider, to line up to the left hand side

**Comment by jobara** [comment]
@cherylhjli I'm not sure I'm seeing this, or maybe just missed it on the page I looked at. Could you please add a screenshot to illustrate the issue?

**Comment by cherylhjli** [comment]
![Screenshot 2023-05-17 at 11 36 20 AM](https://github.com/accessibility-exchange/platform/assets/9353905/54e2c067-7765-4205-bd70-b3855527b8a1)
