### ISSUE TITLE
CC: Default selected on ethnoracial identity

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1692]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
As a CC who has accepted an invitation by an FRO to join an engagement as a CC, and who had to make a new account to do so:
On the edit page step 2 for selecting which communities I can connect to, I noticed the question "Can you connect to a specific ethnoracial identity or identities?" had the "no" radio button selected by default

**To Reproduce**
1. Sign in as an FRO
2. Create an engagement with the recruitment method of CC
3. invite a CC using an email for a user who hasn't created an account yet
4. Create an account as that CC user
5. Go to fill in your public page
6. Go to step 2 and scroll down to the question identified above, see error

**Expected behavior**
For no radio button to be selected by default

**Comment by jobara** [comment]
Sorry, I forgot to file this issue. I had spotted it before and believe it affects any Individual CC creating a public page, but not for Organization CC users.

**Comment by jobara** [comment]
It actually does affect Organization CC users but in the opposite way, where it removes explicitly set "false" values and treats them like null.

See #1739 for a potential solution from a similar issue.
