### ISSUE TITLE
Translatable inputs default to English when the site language is set to LSQ 

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1715]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

When entering a form that contains a translatable input (textarea or textfield) the default translation is English. However, LSQ falls back to French text, so it would make more sense for the default translation to be the French one in this case.

**To Reproduce**
1. Create an organization or regulated organization whose language is LSQ
2. Edit/Create the public page
3. Notice the translatable inputs default to English

**Expected behavior**

Translatable inputs should default to French when LSQ is used.

**Comment by chosww** [comment]
I can't reproduce this issue. I wonder if we didn't have translations for them before and now we have?

**Comment by jobara** [comment]
I can still reproduce this issue. If you try the site in French you can see that the inputs are for the French translation with the option to add an English translation. But with LSQ they inputs are for the English translation with the option to enter a French translation. However, these should both be like the French case where the option is to add the English translation.

Site in French:

<img width="949" alt="Screenshot of Community Org public page creation when site is in French. Inputs are for French translation." src="https://github.com/accessibility-exchange/platform/assets/556024/168b3de3-fcb2-4a27-92a0-da5ccfc9649b">

Site in LSQ:

<img width="937" alt="Screenshot of Community Org public page creation when site is in LSQ. Inputs are for English translation." src="https://github.com/accessibility-exchange/platform/assets/556024/a89df057-676c-4d5b-9b7a-f5875bc8a51a">
