### ISSUE TITLE
Create individual page - checking "something else" under ethnoracial identity

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1753]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I check "something else" under the question
"Which ethno-racial identity or identities are the people you can connect to? (required)*" 
And I don't fill in the text box, and save, this is what the error production looks like: 
![Screenshot 2023-06-06 at 3 31 09 PM](https://github.com/accessibility-exchange/platform/assets/9353905/0c7e9cec-4124-4831-acc4-ae4e615d0911)

However, if I scroll down to the field, the error is not showing up because "something else" has become unchecked: ![Screenshot 2023-06-06 at 3 31 16 PM](https://github.com/accessibility-exchange/platform/assets/9353905/94c4f57f-c6b3-40cb-b3a7-401e9961f0d8)

But if I check the "something else" box again, the error shows up.
![Screenshot 2023-06-06 at 3 34 36 PM](https://github.com/accessibility-exchange/platform/assets/9353905/4efad652-d46e-482c-b7ba-607dab113261)

**To Reproduce**
1. Go to individual page creation, make sure. this user is a CC
2. Go to page 2
3. Select yes for "Can you connect to a specific ethnoracial identity or identities? (required)*"
4. Check something else for "Which ethno-racial identity or identities are the people you can connect to? (required)*", but don't fill in the text field
5. Save and see error

**Expected behavior**
For "something else" to remain selected, therefore the text field below with the inline error appears by default

**Comment by jobara** [comment]
This is probably related to #1692

**Comment by jobara** [comment]
> This is probably related to #1692

Seems that it isn't directly related.
