### ISSUE TITLE
Create project: Who will be going through the results and writing a report?

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1756]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
The copy for this question is currently:  Who will be going through the results from this project and writing a report? (required) 

**Expected behavior**
The copy based on our conversation should be: Who will be going through the results and producing an outcome? (required)*
(to account for the projects that are not strictly writing a report)

The error message should be consistent with the new copy.

**Comment by jobara** [comment]
It looks like the first part of this issue was already addressed but maybe wasn't visible because of the views being cached. However, the validation error message still needs to be updated.
