### ISSUE TITLE
500 error from publishing project page as FRO

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1757]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I clicked publish for a project page as an FRO, I received a 500 error:
![Screenshot 2023-06-06 at 4 37 30 PM](https://github.com/accessibility-exchange/platform/assets/9353905/c765fb35-996c-4a61-aabd-f6fb2e2c10f4)

Not sure if this is a result of this error, but when I tried to make an engagement after I also got a 500 error.

**Comment by jobara** [comment]
I believe this was duplicated by #1761 and was due to the view cache not being cleared properly on the staging site.
