### ISSUE TITLE
Create project: Edit page translations accordion doesn't work

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1758]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I go to edit my project page as an FRO, the edit page translations accordion doesn't work when I click on it.

**Expected behavior**
Open translation accordion.

**Additional context**
This is the project with the 500 error.

**Comment by jobara** [comment]
Will need to investigate further but looks like an issue with AlphineJS, probably with the translation manager blade component.

```error
Alpine Expression Error: x is not defined

Expression: "x-data"

 
<div class="expander stack" x-data="x-data">
[app.20da6a7f.js:3:18583](http://platform.test/build/assets/app.20da6a7f.js)
```

```error
Alpine Expression Error: expanded is not defined

Expression: "expanded.toString()"

 
<button type="button" x-bind:aria-expanded="expanded.toString()" x-on:click="expanded = !expanded" aria-expanded="">[app.20da6a7f.js:3:18583](http://platform.test/build/assets/app.20da6a7f.js)
```
