### ISSUE TITLE
CommOrg getting started: Don't need to create their first project

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1759]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
As a comm org, I shouldn't need to create a project before the getting started module disappears. This is because while creating a project is the whole point why an FRO might be on TAE, that's not the case for CommOrgs. They could also participate as an AC, CC, or CP.

**Expected behavior**
Remove the "create your first project" item on the getting started module.

**Comment by jobara** [comment]
@cherylhjli this was requested feature from IRIS. It came in the attached Testing report Logan sent on May 10, 2023. We [talked about it in the Matrix channel](https://matrix.to/#/!cTDzVKxAmJRmfbSdHL:matrix.org/$Cdoi5S4CfSFbY6cfCM8JgSO5trXLicWp9HrJxg4sJ6I?via=matrix.org). With the final decision being.

> yes, we can add it since IRIS is requesting it. and no it wouldn't block the getting started from disappearing!

[9 May TAE Testing Report.docx](https://github.com/accessibility-exchange/platform/files/11680167/9.May.TAE.Testing.Report.docx)

**Comment by jobara** [comment]
Closing as this is the intended workflow.
