### ISSUE TITLE
League\CommonMark\MarkdownConverter::convert(): Argument #1 ($input) must be of type string, array g...

### ISSUE THREAD

**Issue by marvinroman** [accessibility-in-action/platform#1760]
**`TypeError`**

League\CommonMark\MarkdownConverter::convert(): Argument #1 ($input) must be of type string, array given, called in /app/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 541

:dart: League\CommonMark\MarkdownConverter::convert
:page_facing_up: /app/vendor/league/commonmark/src/MarkdownConverter.php

```php
55    * @throws CommonMarkException
56    */
57*  public function convert(string $input): RenderedContentInterface
58   {
59       $documentAST = $this->markdownParser->parse($input);
```
[Open in Flare](https://flareapp.io/errors/3861175/latest)

**Comment by jobara** [comment]
I believe this was also resolved by clearing the view cache as was done to fix #1761
