### ISSUE TITLE
Estimates and agreements: Not getting open call on the list of engagements

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#1778]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
After filling out the engagement details and adding meetings for an open call engagement, for some reason it's not showing up under the list of engagements I can get a estimate for:
![Screenshot 2023-06-07 at 1 32 26 PM](https://github.com/accessibility-exchange/platform/assets/9353905/54e020df-6172-4843-a370-e61ef984e35a)
![Screenshot 2023-06-07 at 1 32 50 PM](https://github.com/accessibility-exchange/platform/assets/9353905/31264748-f4a3-4afd-950f-952ff5df0542)

**To Reproduce**
1. Create a project
2. Create an engagement with an open call
3. Fill out engagement details
4. Add at least 1 meeting
5. Go to estimates and agreements tab
6. See if the engagement is showing up there

**Expected behavior**
For open call engagements with details and meetings filled out to show up under the estimates and agreements tab.

**Comment by cherylhjli** [comment]
I can't duplicate this.. @jobara if you can't either we can close this.

**Comment by jobara** [comment]
I followed the steps mentioned above, but wasn't able to reproduce the issue. I'll close.
