### ISSUE TITLE
Getting started prompts lack background differentiation in dark mode

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#1801]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

When viewing the Getting started prompts for a community organization in dark mode, there is no background differentiation for the prompt to customize the website's accessibility and invite others to your organization. These are present in all other themes.

**To Reproduce**
1. As a newly-registered community organization user, visit your dashboard.

**Screenshots**

<img width="1230" alt="Prompts in dark mode" src="https://github.com/accessibility-exchange/platform/assets/605361/5f626c54-d796-4374-b332-57d2b7ed04a2">

<img width="1281" alt="Prompts in light mode" src="https://github.com/accessibility-exchange/platform/assets/605361/82d7c6ce-593a-446f-b687-887d242bb49e">

<img width="1240" alt="Prompts in yellow on black" src="https://github.com/accessibility-exchange/platform/assets/605361/ce496502-d590-45fd-961e-9dedf87b2c6a">

**Details**
- Device: any
- Operating system: any
- Browser: any
- Link to affected page: https://platform.test/en/dashboard

**Additional context**
Not applicble.

**Comment by jobara** [comment]
This is interesting. @chosww spotted this before and it was supposed to have been addressed in the original PR (see: https://github.com/accessibility-exchange/platform/pull/1718/commits/09bca15ef5a1ea87de451ef8c1e0a43d2798f595).

**Comment by jobara** [comment]
@greatislander I haven't been able to reproduce this issue. I tried locally and on the dev site (See image below). Where did you encounter the issue and which browser(s) were you using? If you ran into this locally, is it possible that you needed to run a build?

<img width="1260" alt="screenshot showing prompt background in dark theme" src="https://github.com/accessibility-exchange/platform/assets/556024/3f520211-fdb2-4c8d-9f7f-541823448343">

**Comment by greatislander** [comment]
It was local and I guess I hadn't run an updated build.
