### ISSUE TITLE
Unapproved accounts can view resources, projects and individual user's public pages

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1803]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

Only approved accounts should be able to view projects, public pages, and organization pages.

**To Reproduce**
1. Create a new account
2. Before being approved go to the "Projects" and "People and Organizations" tabs. Notice that you can view all of the pages even though the account hasn't been approved yet.

**Expected behavior**

The "Projects" and "People and Organization" links should not be present in the navigation and their entire route paths should not be viewable by unapproved accounts; probably returning 403 errors.

**Comment by michelled** [comment]
Keyanna noted that users can sign up for engagements, even if their page is not published, and account is not approved.

**Comment by chosww** [comment]
hey @jobara, could you tell me how you got to the "Projects" and "People and Organizations" tabs?

**Comment by jobara** [comment]
> hey @jobara, could you tell me how you got to the "Projects" and "People and Organizations" tabs?

@chosww you should see them in the top navigation after you've verified the e-mail address.
