### ISSUE TITLE
Terraform is creating commits on Gitlab causing push issues

### ISSUE THREAD

**Issue by marvinroman** [accessibility-in-action/platform#1866]
When there is a version update, Terraform will push a commit to update versions. This new commit in Gitlab puts Github behind on commits and prevents future commits from automatically being pushed.

**Comment by jobara** [comment]
What I just realized is that each branch (development, staging, and production) is getting these commits. We had been trying to have `production` be a subset of `staging` which is a subset of `dev`. If I'm understanding things correctly, each branch is getting the same change but in a unique commit. Which means that the commit history is different between all of the branches.

**Comment by gtirloni** [comment]
> When there is a version update, Terraform will push a commit to update versions

Can Terraform push commits to the actual repository instead of this mirror?

**Comment by JureUrsic** [comment]
The commits are different true, but can be merged in without a problem with --no-rebase strategy. Terraform is unaware of the original repository, so making commits to it isn't possible, GitLab repos are created and managed by TF completely.

**Comment by jobara** [comment]
It doesn't sound like it's going to be possible in the current deployment setup to have the commits happen directly in GitHub or not at all. In discussing with @michelled we've decided to try the option of having the mirroring GitHub actions to merge from GitLab before pushing to GitLab. If this doesn't work, we'll continue the manual process.
