### ISSUE TITLE
Provide a mechanism for updating staging and dev with data from production

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1903]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to test changes with real data before pushing to production. Being able to pull data from production into staging and dev deploys would help to get a better idea of how new features and fixes affect real data.

**Describe the solution you'd like**

Be able to automatically migrate or have an ability to fetch certain database values from production to populate into staging and dev. This would only be for data that is entered by the service org such as resources, topics, site settings, sign language interpretations and etc. It must **NOT** include user data and account information. 

**Describe alternatives you've considered**

Continue only using fake/sample data for use on the dev and staging site.

**Comment by SantiagoG-Colab** [comment]
@JureUrsic Please add info to this ticket regarding script.

**Comment by jobara** [comment]
Regarding migrating data to staging, will need to consider how this will work with/affect the DevSeeder that would be used to reset the dev site. See: #1902

**Comment by marvinroman** [comment]
**DevSeeder** utilizes 1 of the same seeders that the restore command does. **InterpretationSeeder**. This means that when it's run it will restore from the `.json` backup if it exists.

So if we have a cron the ordering should be.
1. `db:seed:backup -a` (all environments)
2. `migrate:fresh ---seeder=DevSeeder` (specified non-production environments)
3. `db:seed:backup --all --restore --from=production` (specified non-production environments)
