### ISSUE TITLE
French and LSQ translations convert special characters to HTML entity numbers

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#1983]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
I noticed that French/LSQ version of a page converts `'` to `&#039;`. I am assuming any usage of `'` would be translated to that, and there may be other characters behave the same.

**To Reproduce**
1. Go to Dashboard page in English version
2. At the top of the dashboard page, you will see "Customize this website’s accessibility", now change language to either French or LSQ
3. Notice that the apostrophe in the sentence is converted to HTML entity number

**Screenshots**

<img width="1068" alt="Screen Shot 2023-11-17 at 3 45 44 PM" src="https://github.com/accessibility-exchange/platform/assets/22668696/9dd546e0-974c-4636-9aef-bbb90934979f">

**Comment by greatislander** [comment]
Two issues:

1. In translations, curly quotes should always be used, e.g.

```diff
- Personaliser l'accessibilité de ce site Internet
+ Personaliser l’accessibilité de ce site Internet
```

2. In the Blade templates where the Prompt component is used, we should pass translatable strings as PHP variables rather than strings. This will mean that the strings won't be escaped twice. See here: https://laravel.com/docs/10.x/blade#passing-data-to-components


> PHP expressions and variables should be passed to the component via attributes that use the `:` character as a prefix.

```diff
- <livewire:prompt :model="Auth::user()->organization" modelPath="dismissed_invite_prompt_at"
-               heading="{{ __('Invite others to your organization') }}"
-               interpretationName="{{ __('Invite others to your organization', [], 'en') }}"
-               interpretationNameSpace="getting_started-invite_to_community_org"
-               description="{{ __('Please invite others so you can work on projects together.') }}"
-               actionLabel="{{ __('Invite') }}"
-               actionUrl="{{ localized_route('settings.invite-to-invitationable') }}" />
+ <livewire:prompt :model="Auth::user()->organization" modelPath="dismissed_invite_prompt_at"
+               :heading="__('Invite others to your organization')"
+               :interpretationName="__('Invite others to your organization', [], 'en')"
+               interpretationNameSpace="getting_started-invite_to_community_org"
+               :description="__('Please invite others so you can work on projects together.')"
+               :actionLabel="__('Invite') }}"
+               :actionUrl="localized_route('settings.invite-to-invitationable')" />
```
