### ISSUE TITLE
On the deployed sites robots.txt and sitemap.xml are served under the /storage path

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#1998]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

It is expected that the robots.txt and sitemap.xml are served from the root of the site like `https://accessibilityexchange.ca/robots.txt`; however they are accessibly only through the `storage` path like `https://accessibilityexchange.ca/storage/robots.txt`.

**To Reproduce**
1. Go to <https://accessibilityexchange.ca/robots.txt>
2. Notice the 404 error
3. Go to <https://accessibilityexchange.ca/storage/robots.txt>
4. See the contents of the robots.txt file

**Expected behavior**

The robots and sitemap files should be served from the root of the site.

**Comment by jobara** [comment]
It looks like the issue on the deployed site is because the `public` disk actually stores to the `\storage` directory and is configured to expose this at `env('APP_URL').'/storage'`. I'm not sure why locally it also exposes it off the root, but maybe there is something in Herd or other local environment configuration that is handling this.

**Comment by greatislander** [comment]
@jobara I'm wondering if this solution is necessary. It looks like you can create links?

https://laravel.com/docs/10.x/filesystem#the-public-disk

**Comment by greatislander** [comment]
is `php artisan storage:link` being run on production and local environments?
