### ISSUE TITLE
Email verification flash message not localized

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2012]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**

The success flash message informing that the email address has been verified is not localized.

**Expected behavior**

The message should be localized.

**Screenshots**

<img width="360" alt="Screenshot of flash message for email verification not properly localized" src="https://github.com/accessibility-exchange/platform/assets/556024/4827eba1-d792-4aba-9010-5eff02e7a394">

**Comment by jobara** [comment]
This message should be coming from `hearth::auth.verification_succeeded` for which there is already a French translation. It isn't clear at the moment why this isn't working.

**Comment by chosww** [comment]
@jobara I can't reproduce this locally

**Comment by chosww** [comment]
<img width="837" alt="Screen Shot 2023-11-30 at 10 43 50 AM" src="https://github.com/accessibility-exchange/platform/assets/22668696/be231c33-4cf5-4002-a21f-0103cace19b6">

Works fine on Dev site as well; closing this issue, since it is not reproducable.

**Comment by jobara** [comment]
was reproduced
