### ISSUE TITLE
French FRO accounts receive approval email notifications in English

### ISSUE THREAD

**Issue by colinbdclark** [accessibility-in-action/platform#2015]
**Prerequisites**

- [x] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

**Describe the bug**
When I create an account with the language set to French, and my account type is for an FRO, I receive a confirmation email in English after an administrator has approved my account.

However, when I do this same process with a French account as an Individual, I correctly get the confirmation email in French.

**To Reproduce**
1. Set the language to French
2. Create a new FRO account
3. As an administrator, approve the account

**Expected behavior**
All communication with an account whose language is set to French should be in French

**Screenshots**

**Details**
![Screenshot 2023-11-28 at 3 48 12 PM](https://github.com/accessibility-exchange/platform/assets/558076/36a83323-67be-4254-bd52-73585cea054c)
![Screenshot 2023-11-28 at 3 48 32 PM](https://github.com/accessibility-exchange/platform/assets/558076/d0257107-3746-47a8-9b2e-5b33bca153ab)

**Comment by michelled** [comment]
The account verification email also contains a mixture of English and French. 
<img width="475" alt="Screen Shot 2023-11-30 at 12 52 06 PM" src="https://github.com/accessibility-exchange/platform/assets/562893/6906f0f9-498b-45e9-b4a2-88ad952a5d0f">

**Comment by chosww** [comment]
I noticed that some messages don't have French translations; ones we need translations for:

AccessNeedsFacilitationRequested

- :name requires access needs facilitation
- Requires access needs facilitation

AccountApproved

- You are now able to publish your page and create projects and engagements.
- You are now able to publish your page and sign up for projects.
- You are now able to sign up for projects.

AccountSuspended

- Please contact us if you need further assistance.
- You will not be able to edit any information in your account.
- You will not be able to edit any information in your account. Your page will no longer be shown to other users of this website.

AccountUnsuspended

- Please contact us if you need further assistance.
- You will be able to edit your information and browse projects and people on this site again.

**Comment by colinbdclark** [comment]
Thanks, @chosww. Just to confirm, are these strings in CrowdIn so that the translator can go ahead and translate them?

**Comment by chosww** [comment]
Currently, email verification email is not localized as @michelled noticed. I added localization keys to PR #2050. We should prioritize translation of the email messages.
