### ISSUE TITLE
English string appear in the French version of the Resources page

### ISSUE THREAD

**Issue by colinbdclark** [accessibility-in-action/platform#2026]
### Prerequisites

- [X] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

When using the French language, a user sees English strings in several of the Resource Type sections.

### To Reproduce

1. Go to https://accessibilityexchange.ca/fr/resources/collections/the-accessible-canada-act
2. Open the Secteur and Domaine d'impact types

### Expected behavior

These strings should appear in French.

### Screenshots

![Screenshot 2023-11-29 at 12 03 44 PM](https://github.com/accessibility-exchange/platform/assets/558076/7929052e-b813-4d16-8c92-202bd47c7064)

### Additional context

According to Samuel, several of these strings were translated in CrowdIn but aren't appearing. He asked: "is it possible they use the other json file for this part of the website? because the 'secteur' menu hasn't updated either."

**Comment by colinbdclark** [comment]
Samuel also notes that "these strings do not show up translated in the profile creation pages either (same strings)." See attached screenshot.
![Screenshot 2023-11-29 at 12 11 33 PM](https://github.com/accessibility-exchange/platform/assets/558076/e0e8b2cd-6548-4c33-9e4d-7e704a9e5587)

**Comment by jobara** [comment]
Appears to be related to #2014
