### ISSUE TITLE
Node ping errors nightly on dev during database reset

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2042]
### Prerequisites

- [X] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

When the dev site's database is reset nightly, around 3am ET, the site is put into maintenance mode. During this period the node pings fail and send out an error report. This is not a true failure as the dev site is expected to be in maintenance mode at this time.

### Expected behavior

There shouldn't be any error alerts if the site is in maintenance mode during this expected time. However, if it isn't removed from maintenance mode in a reasonable amount of time, it should trigger an alert.

### Additional context

See [discussion](https://github.com/accessibility-exchange/platform/issues/1867#issuecomment-1814966474) about the health check on #1867.

The options would seem to be something along the lines of:

- Modify the health check
- Do not put the site into maintenance mode. This could mean that database is reset while someone is in the middle of interacting with it. They'll get errors, at least with their session but possibly also user account, and any data they are trying to save.

**Comment by jobara** [comment]
It looks like this may also be causing a session error, possibly from the health check.

**Comment by SantiagoG-Colab** [comment]
@jobara Reviewing this with @marvinroman, he will review this with @JureUrsic, specifically to decide how to split the checks.
