### ISSUE TITLE
Organizations' contact person email can be a user not registered in the platform

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#2053]
### Prerequisites

- [X] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

This is a follow up issue from #2050, where we are setting preferred locale for notifications to be contact person's locale. Because contact person's email can be an email that doesn't belong to a user in the platform, we can't fetch their locale, so emails we send out can be in language they don't use.

### To Reproduce

Steps to reproduce the behavior (after #2050 gets merged):
1. Create an organization or regulated organization
2. Edit the contact person information from the organization's page, use email that doesn't belong to a user from the platform
3. Log out from the account and sign in with the platform admin account
4. Go to account manage section, and suspend the organization's account
5. Check the email sent to the contact person's email, notice it's in the language of the admin panel when the suspension was happening

### Expected behavior

Email should sent in contact person's working language.

**Comment by jobara** [comment]
We may need to add settings for contact language. @cherylhjli do you have thoughts on this?

**Comment by jobara** [comment]
In talking to @cherylhjli about this today, it seems that it would make more sense to not send system e-mails to the contact person. Rather these should only go to the org admins/memebers as necessary. The contact email is really for external communication and appears on the public page.

**Comment by jobara** [comment]
@cherylhjli I was looking into this. The system is actually setup to send all of the internal notifications to an orgs contact person. In talking about this yesterday we were thinking that the contact person mentioned for the org was just for external communications. Is that correct? Does that mean that all org admins should get the emails instead?

**Comment by cherylhjli** [comment]
@jobara Yes I think yesterday I was under the impression that the contact person that someone can add in the org's profile page is just for external communications. I think it would help to know what all the systems emails are for - if it's for things like verifying an email address, then it makes sense for org admins to get that email. But if an agreement or estimate has been approved, then the project contact would make more sense. Maybe we can discuss in January.

**Comment by jobara** [comment]
It looks like for projects and organizations the person to be notified is set through `routeNotificationForMail` and is currently set to the contact person. I'm not sure if this can take in multiple e-mail addresses or if instead at the site that `notify()` is called, we'd have to loop through the admins. If we want to have different cases for who to notify we may have to do it at the place where `notify()` is called.

**Comment by cherylhjli** [comment]
In convo with @jobara 

Use cases:
- CO notified about being invited as a consultation participant for an FRO engagement - notify org admin
- CO notified about being removed as a consultation participant for an FRO engagement - notify org admin
- CO notified about being invited as a community connector to an engagement - notify org admin
- CO notified about being removed as a community connector to an engagement - notify org admin
- CO/FRO notified that the community connector accepted their invite for an engagement - notify project contact
- CO/FRO - Engagement related - an individual signs up for your open call engagement - notify project contact
- CO/FRO - Engagement related - an individual leaves for your open call engagement - notify project contact
- CO/FRO - Engagement related - an individual accepts the CC's invitation to join the engagement - notify project contact and CC
- CO/FRO - Engagement related - an individual declines the CC's invitation to join the engagement - notify project contact and CC
- CO/FRO - When you successfully send an invite to a CC to join your engagement - notify project contact
- When an estimate is returned for a project - notify project contact
- When the agreement is received for a project - notify project contact

**Comment by jobara** [comment]
@cherylhjli just noticing that the project related emails go to the project contact person. However, again this can be for an email address that isn't registered as a user in the system and we don't know what language to send it in, so it will always send in English.

**Comment by jobara** [comment]
In the [matrix channel discussion](https://matrix.to/#/!QRQCoXAWrIjYQVYaai:matrix.org/$mrK4yWb5DSX89ZjPSSgM7Dj-sZsR8IDJa5WiTn3Gkx0?via=matrix.org), @cherylhjli agreed that we could add a preferred language option. If possible we could pre-select the value set in the "What language(s) does your organization work in?" if there is only a single one picked.

**Comment by jobara** [comment]
I had a [follow up conversation](https://matrix.to/#/!QRQCoXAWrIjYQVYaai:matrix.org/$ar6oyvJLHWxkof6vSSqne0Q9RSVjA3kVtAhPWkOmwZs?via=matrix.org) with @cherylhjli in the matrix channel. We've decided for now to send the org emails to the contact person after all and to add a preferred contact language option for them.
