### ISSUE TITLE
Dashboard notifications are always in English

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#2055]
### Prerequisites

- [X] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

Dashboard notifications are in English even for the French/LSQ users. 

### To Reproduce

1. Create an account in French or LSQ as selected language
2. Sign in as the platform admin and approve the account
3. Sign back in to the platform as the user, and go to the dashboard page
4. See that the notifications messages are in English

### Expected behavior

Notification messages should be in User's selected language.

### Screenshots

<img width="922" alt="Screen Shot 2023-12-07 at 11 28 35 AM" src="https://github.com/accessibility-exchange/platform/assets/22668696/520dc21c-ba1c-427f-80fb-7cbefbc7a37b">

### Additional context

Some part of the notification messages are in French.

**Comment by chosww** [comment]
I can't reproduce this issue anymore.

**Comment by jobara** [comment]
This may have been addressed with some of the recent French translations that were added.
