### ISSUE TITLE
Change the name of the email sender to clarify when emails are being sent from the staging site

### ISSUE THREAD

**Issue by colinbdclark** [accessibility-in-action/platform#2058]
### Is your feature request related to a problem? Please describe.

At the moment, emails (such as estimate requests and approvals) from both the Production and Staging instances of TAE are sent from "The Accessibility Exchange." This makes it difficult to know, at a glance, if an email is being sent as part of testing or if it's a request that our support team needs to respond to for real.

### Describe the solution you'd like

Could we have the name of the sender of emails from the staging site being something like "The Accessibility Exchange Staging" or something that distinguishes it from the emails sent from the production site?

### Additional context

This isn't a huge blocker or anything like that, but if it's not too complex would be a big quality of life improvement for the support team.

**Comment by jobara** [comment]
I've changed the dev site's Sender name to "The Accessibility Exchange (Dev)" and the staging one to "The Accessibility Exchange (Staging)". These should be picked up after the next deployment. For staging that will be with the next release. ( probably v1.2.5).
