### ISSUE TITLE
The Quick Exit link takes users to weather.com

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2074]
### Prerequisites

- [X] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

The purpose of the Quick Exit is to allow users to be discrete about browsing TAE. However, taking users to a US weather website for Ottawa may not have the desired effect.

### To Reproduce

1. In the top right corner click "Quick Exit"
2. Notice you are taken to weather.com searching for Ottawa weather

### Expected behavior

The Quick Exit should direct users to a page that they would more likely be using.

**Comment by jobara** [comment]
@colinbdclark do you have suggestions for a better interaction or destination for the Quick Link?

**Comment by colinbdclark** [comment]
How about just sending them to google.ca?

**Comment by jobara** [comment]
Another suggestion is to use https://www.theweathernetwork.com/ca which seems to pick the weather location based on the users ip or some other mechanism for finding locale.

@colinbdclark how do you feel about this?

**Comment by cherylhjli** [comment]
Google is better than weather website - I think most folks check their weather on mobile, which may make being on the website on a desktop browser suspicious.
