### ISSUE TITLE
Add models related to site data to filament so that admins can update/edit them

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2080]
### Is your feature request related to a problem? Please describe.

Related to #2077 there are a number of model's for data that the site uses. These should be editable by the admin.

### Describe the solution you'd like

Add model's to the filament admin panel.

Models to be added to filament:

- AccessSupport
- CommunicationTool
- ContentType
- Impact
- Language (? see how this is used in the system)
- PaymentType
- Sector

**Comment by jobara** [comment]
It looks like the Language models are used for the constituency connections. These are usually created when the options are selected so it doesn't need to be in filament. However, it may still be useful for pre-populating or editing/removing.

**Comment by jobara** [comment]
@cherylhjli I need to add logos in the filament admin interface for each of the items here. They show up in a side navigation (see screen shot)

![Screenshot of filament navigation](https://github.com/accessibility-exchange/platform/assets/556024/dfe50760-9365-4396-af47-0ffcd9b997f7)

Can you confirm/recommend/provide icons for these? (icons mentioned are from [heroicons](https://heroicons.com/solid))

- AccessSupport (?)
- CommunicationTool ( chat-bubble-bottom-center-text ) 
- ContentType (document)
- Impact (cursor-arrow-ripple)
- Language (language) -- or we could use part of the language icon we use for the site.
- PaymentType (wallet)
- Sector (building-library)

**Comment by cherylhjli** [comment]
@jobara 

- What does "communication tool" entail again? Is the preferred contact method (whether someone can use phone or email)?
- What does "content type" entail again? Is it the format a resource is in?
- Is "sector" the FRO types? If so, building-library works.
- Is "impact" areas of the ACA, ex. communications, employment, etc? If so can we rename it to "Areas of Accessibility Planning"? And then use maybe.. clipboard?
- Language: Yes let's use the language icon we use for the site
- Payment type - the wallet doesn't really look like a wallet.. can we use the icon banknotes or currency-dollar?
- For Access support, maybe.. scale? or sparkles?

**Comment by cherylhjli** [comment]
In convo with @jobara 
- Communication tool - remove
- content type - for resources - the document icon is already quite similar to the icon for resources, why don't we try square-3-stack-3d?
- Impact - will make future issue for renaming. Squares-2x2 might match the future name of "Areas of accessibility planning", but I think signal matches the current name of "impact" more. Take your pick!
- language - give the double icon a try, if it's awful then use language icon on heroicons
- access supports - sparkles

**Comment by jobara** [comment]
@cherylhjli I filed new issues for the removal of Communication Tool ( #2109 ) and renaming Impact to "Areas of accessibility planning" ( #2110 ).

**Comment by jobara** [comment]
> * Impact - will make future issue for renaming. Squares-2x2 might match the future name of "Areas of accessibility planning", but I think signal matches the current name of "impact" more. Take your pick!

I'll use Squares-2x2 as we are planning to change the name.

> * language - give the double icon a try, if it's awful then use language icon on heroicons

tried the double icon we have, but it ended up being very small because it was matching the widths of the other icons. So I switched to use heroicons' language icon.
