### ISSUE TITLE
Improve the sign up/getting started workflow

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2142]
### Prerequisites

- [X] I've [searched](https://github.com/accessibility-exchange/platform/issues) for existing issues

### Describe the bug

As currently implemented, users are finding it confusing which steps need to be performed as part of the registration and getting started. In particular they have been unsure which roles they should be selecting. Usually going to an orientation session makes it more clear which role they should be applying for, but the orientation session sign up happens after role selection.

**Comment by jobara** [comment]
@cherylhjli has been designing a new workflow for this process. For one, the role selection is moved to happen after the user has been oriented.

- [Workflow](https://www.figma.com/file/XOoL9fwVQ2mxt9t6qOBXWv/TAE-User-Flows?type=whiteboard&node-id=7-1143&t=9Oc73P4StpDccBMz-0)
- [Wireframes](https://www.figma.com/file/5J9uimqjouSxBJW6JR6uZl/Wireframes---ALL?type=design&node-id=1-29370&mode=design&t=1nErgMWGyl1aahnr-0)

**Comment by michelled** [comment]
IRIS would like to move to a single form instead of two - they will provide the new link.

**Comment by jobara** [comment]
> @cherylhjli has been designing a new workflow for this process. For one, the role selection is moved to happen after the user has been oriented.
> 
> * [Workflow](https://www.figma.com/file/XOoL9fwVQ2mxt9t6qOBXWv/TAE-User-Flows?type=whiteboard&node-id=7-1143&t=9Oc73P4StpDccBMz-0)
> * [Wireframes](https://www.figma.com/file/5J9uimqjouSxBJW6JR6uZl/Wireframes---ALL?type=design&node-id=1-29370&mode=design&t=1nErgMWGyl1aahnr-0)

In discussion with IRIS they would prefer to keep the AC and CC roles despite limitations with the current approval system.

**Comment by jobara** [comment]
Until we move the orientation and application forms into TAE we won't know when they are completed. In the designs there are separate steps for sign up and attending the orientation for example. After speaking with @cherylhjli in the [matrix channel](https://matrix.to/#/!QRQCoXAWrIjYQVYaai:matrix.org/$hkTfEF2FKsWfGMwaR-uMmZdtdrfTfueR4TeOcltMk1U?via=matrix.org) we will combine these steps into one with copy like "sign up and attend orientation".

**Comment by jobara** [comment]
Additional tasks related to this work have been filed as:

- https://github.com/accessibility-exchange/platform/issues/2199
- https://github.com/accessibility-exchange/platform/issues/2200
- https://github.com/accessibility-exchange/platform/issues/2201
