### ISSUE TITLE
Allow the site to be accessed via a French domain

### ISSUE THREAD

**Issue by jobara** [accessibility-in-action/platform#2277]
### Is your feature request related to a problem? Please describe.

While the site is localized in French/LSQ and English/ASL, the domain is only in English. The request is to be able to access the site also from https://connecteuraccessibilite.ca

### Describe the solution you'd like

- Use https://connecteuraccessibilite.ca and https://www.connecteuraccessibilite.ca as aliases for the site.
- When using the French domain the default language of the site should be French instead of English

### Describe alternatives you've considered

An additional option would be for the site to always use the French domain when the language is French/LSQ and the English domain when the site is English/ASL. However it would be more complicated to switch between languages and may also be confusing for users as it may appear to be changing to a different site. Another potential issue is that the session wouldn't automatically transfer over and would require the user to log in again if the session couldn't be passed along.

### Additional context

@marvinroman has done some investigation into this with regards to using nginx configuration and custom middleware.

There's also the possibility of using something like https://github.com/gecche/laravel-multidomain

**Comment by jobara** [comment]
@greatislander mentioned that having the two alias urls as described above would likely affect SEO. His suggestion instead is to have a bilingual url such as https://tae-ca.ca which the existing https://accessibilityexchange.ca redirecting to https://tae-ca/en and https://connecteuraccessibilite.ca/ redirecting to https://tae-ca/fr. In this way there is a single canonical domain name.

**Comment by marvinroman** [comment]
Yeah having aliases instead of dedicated domains would likely affect SEO. I was assuming most of the site is behind a login screen so SEO wouldn't be super important but that assumption might be wrong.

**Comment by jobara** [comment]
> @greatislander mentioned that having the two alias urls as described above would likely affect SEO. His suggestion instead is to have a bilingual url such as https://tae-ca.ca which the existing https://accessibilityexchange.ca redirecting to https://tae-ca/en and https://connecteuraccessibilite.ca/ redirecting to https://tae-ca/fr. In this way there is a single canonical domain name.

Waiting to hear back from Erick regarding this approach with a bilingual url.

**Comment by jobara** [comment]
This was resolved by:

- The English domain ( https://accessibilityexchange.ca ) is the canonical one
- The French domain ( connecteuraccessibilite.ca ) redirects to accessibilityexchange.ca/fr
