### ISSUE TITLE
Potentially revert #2351 after upgrading to Pest v3

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#2352]
We may be able to revert #2351 after we upgrade to Pest v3 and PHPUnit v11.

**Comment by jobara** [comment]
See conversation in accessibility exchange channel https://matrix.to/#/!QRQCoXAWrIjYQVYaai:matrix.org/$U9Mky16eppoJPRaSNFbiX2FGRbYyMtvcuI4CwBb-ueM?via=matrix.org

https://github.com/sebastianbergmann/phpunit/pull/5225 should have fixed the upstream issue in phpunit, allowing named parameters to be used from the datasource. It seems that Pest v3 should also now support this, except the case where the parameters count mismatches ( https://github.com/pestphp/pest/issues/1232 ).
