### ISSUE TITLE
Home Pages: Create account and Sign in buttons are too far from the rest of the content

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#761]
A person using magnifier at 350% missed the create account and sign in buttons on the right. There is too much white space between the logo and the buttons, thus, user assumed there is no more content on the right. 
There was a recommendation to move the buttons to the top navigation right before the quick exit or somehow closer to the logo.

**Comment by cherylhjli** [comment]
Since it's my understanding that resources are not public, I think we can move "create an account" and "sign in" to be left aligned on the navigation bar - signed out state: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1134%3A11771

**Comment by sepidehshahi** [comment]
That sounds good @cherylhjli and it will solve the problem

**Comment by michelled** [comment]
After looking at this more with @greatislander and @jobara we think that it would actually be better to leave the sign in and create account on the right. This seems to be the place that most sites put the sign in link so it's the place that many people look for the link. The recommendation when using a magnifier is to use the browser zoom first to get the responsive layout and then use the magnifier as required. In the responsive layout, the sign in will not be on the right side.
