### ISSUE TITLE
Italicized text is not easy to read when using magnifiers.

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#763]
User had to increase the zoom level and eventually use the text to speech function of the magnifier where text was italicized.

**Comment by cherylhjli** [comment]
@greatislander I have changed the hint text type treatment for any form field inputs from italics & graphite 6 to regular body & graphite 7.

Other pages that had italics...
(these are all in the wires, which have updated copy)
G
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=2613%3A68551
"Please check all that apply"

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1725%3A47554
"This can be paid or volunteer work"

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1725%3A47515
"These are the seven areas..."

https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1295%3A15858
"Please tell us where your organization's headquarters are located"
