### ISSUE TITLE
Individual page creation: save and save next buttons placement

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#764]
- [ ] Remove the set of Save, Save next, and Save previous from the top of the form. They make it very overwhelming for the magnifier users
- [ ] Place Save and Save next next to each other. Magnifier user missed the save next button

**Comment by cherylhjli** [comment]
This makes sense to me - we can remove the buttons at the top of the page, and only have the buttons at the bottom.
For these buttons @greatislander, could we either:
- increase the button width so there is only max 30px space between them (make them fill the column width), or
- not have them fit the width of the column, and just have them next to each other with 30px space in between them
