### ISSUE TITLE
Create profile - groups you can connect to: Languages field should be optional

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#782]
This should not be required - for example if the languages used by the people I can connect to are English, I don't think it's necessary to add anything.

Also, currently the field has "(required)" on it but it doesn't produce an error when it's not filled in!

**Comment by greatislander** [comment]
@cherylhjli Individual or organization?

**Comment by greatislander** [comment]
Optional for both individuals and organizations
