### ISSUE TITLE
Error loading projects page as community org

### ISSUE THREAD

**Issue by michelled** [accessibility-in-action/platform#789]
Steps to reproduce:
1. Create a community org account
2. Select the Dashboard
3. Select the Accessibility Exchange link on the verify your email page
4. Select Projects

Results:
404 Not Found error

**Comment by greatislander** [comment]
Solution: remove "Projects", "People and Organizations", and "Resources" from navigation for those who haven't yet verified their emails.

**Comment by cherylhjli** [comment]
I can still access projects, people and organizations, and resources and training as an unverified individual. Is this supposed to happen? @greatislander

**Comment by greatislander** [comment]
Unverified meaning "haven't verified your email?" @cherylhjli

**Comment by cherylhjli** [comment]
yes!
