### ISSUE TITLE
Create a new community org: Name - 404 error

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#805]
Path:
- Create an account as a community org
- Picked representative org as the org type
- Entered a name in the French name field (IDRC and IRIS, tried both of these in separate attempts)
- Got an error saying there's already an organization with that name
- Tried to enter a different name in the French name field still (ex. Inclusion Canada)
- Got a 404 error

![Screen Shot 2022-08-15 at 11 23 16 AM](https://user-images.githubusercontent.com/9353905/184665000-f1f05a4d-d201-4d95-b128-b69f90bc472b.png)

When I go back to the home page, it shows my name in the top nav bar - 
![Screen Shot 2022-08-15 at 11 27 01 AM](https://user-images.githubusercontent.com/9353905/184665329-3812aa22-6cfe-413d-9a6d-ac4bee297b1f.png)

But when I go to the dashboard I get a 500 error.

I've replicated this twice.

**Comment by greatislander** [comment]
https://flareapp.io/errors/1489800

**Comment by greatislander** [comment]
If you only enter the name of an organization in a language other than the current language, a 404 occurs because there is no slug in the current language. I am doing some tests to see where else this might be an issue.

The 500 error was the result of organization roles not being selected prior to visiting the dashboard. I've resolved this in #810.

**Comment by michelled** [comment]
@greatislander I merged your fix, however when I tested on the dev build I'm still seeing the 404

**Comment by greatislander** [comment]
@michelled I think the two deploys ran at the same time from the two PRs that were merged and the second one (for this) failed. I ran it again via https://github.com/accessibility-exchange/platform/pull/813 and then tested and it seems to be fixed now. I'm going to close this but we can reopen if we identify any further issues.
