### ISSUE TITLE
Comm org: Select language - "Choose language" counts as a language

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#806]
Path:
- create community organization page
- pick page translations
- add language
- didn't pick a language (left dropdown at "choose a language...") - clicked "add language"
- "choose a language" shows up as a language that can be removed
- If then I click "create organization", a 500 error shows up

![Screen Shot 2022-08-15 at 11 34 25 AM](https://user-images.githubusercontent.com/9353905/184666858-fd5af177-8a93-45a0-985b-850c21e44956.png)

![Screen Shot 2022-08-15 at 11 34 37 AM](https://user-images.githubusercontent.com/9353905/184666878-92ced1bd-ddfe-40aa-bba5-95c05aff1e7d.png)

**Comment by greatislander** [comment]
https://flareapp.io/errors/1489809
