### ISSUE TITLE
Community org page creation: Groups you can connect to - fields not saving

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#808]
The following fields are not saving:
- [ ] When I select “yes” for “does your organization specifically represent people who are marginalized baed on gender or sexual identity”, a list of checkboxes show. If I select one or more, it doesn’t save.
- [ ] When I select anything under “do you specifically represent people with disabilities, Deaf persons, and or their supporters”, it doesn’t save.

**Comment by greatislander** [comment]
I can't reproduce this, @cherylhjli — we will need to connect about this tomorrow.

**Comment by michelled** [comment]
@greatislander I saw this issue by not filling in a required field before I saved. I got a list of the errors at the top and those two selections had been cleared.

**Comment by cherylhjli** [comment]
@greatislander This seems to be resolved, but now the field "please select people with disabilities that you specifically serve and support" doesn't seem to be saving if I select "specific disability or disabilities". Should I reopen this or start a new issue?

**Comment by greatislander** [comment]
New issue, please.
