### ISSUE TITLE
FRO page creation: Replace create page link with a button

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#827]
On the user dashboard, where user can start creating a page, replace the "create page" link with a button similar to what we have on the individual dashboards. The link was difficult to find for magnifier user.

**Comment by sepidehshahi** [comment]
@greatislander This will be addressed in the simplified dashboard. However, if you don't do the simplified dashboard please fix this.

**Comment by michelled** [comment]
@sepidehshahi @greatislander is this one done?

**Comment by greatislander** [comment]
Yes.
