### ISSUE TITLE
Add language modal dosn't get the focus

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#833]
When adding a language, whether creating an organization or a project, the focus doesn't go directly to the "Add Language" modal and it remains on the main area.

**Comment by cherylhjli** [comment]
@sepidehshahi please test this

**Comment by sepidehshahi** [comment]
The issue has been resolved and I couldn't reproduce this.

**Comment by greatislander** [comment]
Can't reproduce this issue.
