### ISSUE TITLE
English language can't be removed from page translations

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#834]
When creating an organization page or a project, on the page/project translation page there are four languages by default. 

- [ ] Selecting the remove button for English would remove other languages.
- [ ] If English is the default language we shouldn't show the remove button

**Comment by greatislander** [comment]
Can you give me some more info about this, @sepidehshahi? Is French added? Is the site being used in French?

**Comment by greatislander** [comment]
Resolved by #861. Duplicate of #856.
