### ISSUE TITLE
Community Org page creation: Step 4/4 - Preferred contact method: Can select phone even with no phone number inputted

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#850]
- I made an account as a community organization
- Filled out my page, got to step 4 - contact info
- Phone number showed up as an option for preferred contact method, even if no phone number was entered

Is that intentional? I was under the impression that the phone option would only show up if there was a phone number entered!

**Comment by greatislander** [comment]
If you select it you will get an error if you haven't entered a phone number, though. Dynamically changing that field was proving to be a real pain in the neck and also logically it would need to disappear unless both contact methods were entered— which we've heard was confusing/disorienting in some other situations. So I figured it was simpler to have it there and warn people if they haven't entered the right data.

**Comment by cherylhjli** [comment]
make sense thanks!
