### ISSUE TITLE
Community Org page creation: Step 4/4 Contact info - can save without email

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#851]
On this page, I can successfully save the page without having any email filled in. I was under the impression that the email is required, since it's also the email a user would use to log in?

**Comment by cherylhjli** [comment]
Related: On the notifications page, because there is no email saved, the "preferred notification method" did not pick "email" by default

**Comment by greatislander** [comment]
This is correct— it's different from individuals where the user's email is the email contact method. When a new community org or FRO is created, the contact email is automatically populated with the administrator's email. However, if the contact person for the organization is someone else, they can either change that email (it doesn't also change the admin user's email) or switch to using a contact phone.

**Comment by cherylhjli** [comment]
makes sense thanks!
