### ISSUE TITLE
Community org page creation: Filled in information during page creation but dashboard still shows "create your page" rather than edit

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#852]
- Created account as community org
- Jumped to page 2 in the page creation flow (without filling in other pages)
- Filled in information and hit save - successfully saved
- Didn't fill out any other page
- When I click back to dashboard, dashboard shows this:
![Screen Shot 2022-08-17 at 3 50 07 PM](https://user-images.githubusercontent.com/9353905/185229767-9ff57d54-1150-40f6-9605-f4d061a76fee.png)

- When I click "create your page", I go to the "page translations" page
- When I go back to the page I filled out (step 2), the content has saved

**Comment by greatislander** [comment]
Related to #595. It should show "edit" if information has been added on any page.

**Comment by greatislander** [comment]
No longer relevant.
