### ISSUE TITLE
FRO page creation: When user selects phone for contact method, and there's no phone number, no error occurs

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#863]
On the tails of this.. https://github.com/accessibility-exchange/platform/issues/850

When I was creating a page for an FRO user, I picked phone for "preferred contact method". However I didn't enter a phone number. I was able to save with no error. 

This also occurs when I pick email for "preferred contact method", but no email was entered.

Desired behaviour:
Produce an error notification that says:
"Error
[Phone/Email] was picked for your preferred contact method. However, there is no [phone number/email] filled in. Please fill this in and try again."
Inline error says under the phone number/email field:
"Please fill this in"

**Comment by greatislander** [comment]
Resolved in #1160.
