### ISSUE TITLE
Mobile: language list doesn't appear on the add language modal

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#869]
Android 12/ talk back/ Chrome 

When opening the "Add language" modal from different places, the list of languages is not shown in the drop down menu.

**Comment by sepidehshahi** [comment]
@sepidehshahi test this one

**Comment by greatislander** [comment]
@sepidehshahi I couldn't reproduce this— can you let me know if it is still an issue?

**Comment by michelled** [comment]
This could not be reproduced.
