### ISSUE TITLE
Mobile: Announce when you are at the end of the page translations links

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#874]
Android 12/ Talk back/ Chrome

When "Change page language" menu is expanded, user can navigate from the links on this menu to the links on the main page without any notification that they are moving from one menu to another. For example on a project page, if they have expanded the "change page language" when they get to the "Contact support" link, the next link is "project overview. This was confusing for the user. Adding an announcement that says you are at the end of language options or you are moving to another set of links would be helpful.

**Comment by greatislander** [comment]
I think we are removing this altogether, right? and linking to the page where you can add/remove languages instead.

**Comment by greatislander** [comment]
@cherylhjli is that right? ☝🏻

**Comment by cherylhjli** [comment]
@greatislander @sepidehshahi yes we are removing the accordion altogether!
