### ISSUE TITLE
Account creation: Replace the heading "Your role" by "who you're joining as"

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#876]
Change the heading "Your role" to "who you're joining as" on the second step of the account creation process as we use the same term for individual roles (CP/AC/CC).

**Comment by cherylhjli** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A4237

**Comment by greatislander** [comment]
Resolved a long time ago, not sure exactly when.
