### ISSUE TITLE
Create new project: Project start date produces 500 error

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#879]
- Sign up as an FRO
- create new project
- Go to project start date - by default it's populated with today's date
- Go into the dropdown and pick "choose a month"
![Screen Shot 2022-08-18 at 4 14 09 PM](https://user-images.githubusercontent.com/9353905/185492568-69166054-6429-4e7c-809c-1e80d3be8bd1.png)

- A second later this comes up, I think as a pop-up / overlay?
![Screen Shot 2022-08-18 at 4 14 02 PM](https://user-images.githubusercontent.com/9353905/185492551-e0939245-ebce-45e7-a9e6-c5c6d579e9b0.png)

This also happens with the end date field!

Not sure what the priority for this should be - putting it as for the next release but please feel free to deprioritize if need be.

**Comment by greatislander** [comment]
Duplicate of #832.
