### ISSUE TITLE
Project creation flow: Start date / end date year picker

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#880]
Using the up/down arrows in the year picker, I can't go before 2022!

**Comment by greatislander** [comment]
Is this not correct? Projects aren't being created before September/October 2022. So for the start date and the end date, why would the year picker let you enter older projects?

**Comment by sepidehshahi** [comment]
Is there a case that they have started a project already, let's say in 2021 and they will use the platform for creating further engagements or follow up reports?

**Comment by greatislander** [comment]
Possibly? I wasn't sure when these projects had been started. I assumed January 2022 was a good safe bet for what would be migrating to the platform. We can change the date to 2021 though.
