### ISSUE TITLE
Viewing a project with no training crashes the application on "Project team" tab

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#888]
Because the project team page lists all the trainings and the blade template is trying to access undefined information about the trainings, the application crashes.

Error message:

Undefined array key "name" -- resources / views / projects / partials / team.blade.php : 49

**Comment by greatislander** [comment]
Identified on the dev site: https://flareapp.io/errors/1493783

**Comment by greatislander** [comment]
Resolved in #913.
