### ISSUE TITLE
Engagement details: Payment amount for surveys, asynch interviews, other async

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#890]
Add field for payment amount for these consultation formats. Waiting on Michael / IRIS for confirmation of how payment works for these formats.

**Comment by greatislander** [comment]
@cherylhjli what's the status on this info?

**Comment by cherylhjli** [comment]
No response from email sent 2 weeks ago. Just followed up.

**Comment by greatislander** [comment]
We won't need this.
