### ISSUE TITLE
File does not exist at path /opt/data/storage/framework/views/61cb24237d9772f79862641d9038616e2af923...

### ISSUE THREAD

**Issue by greatislander** [accessibility-in-action/platform#906]
**`Illuminate\Contracts\Filesystem\FileNotFoundException`**

File does not exist at path /opt/data/storage/framework/views/61cb24237d9772f79862641d9038616e2af923b3.php.

:dart: Illuminate\Filesystem\Filesystem::getRequire
:page_facing_up: /app/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php

```php
109          }
110  
111*         throw new FileNotFoundException("File does not exist at path {$path}.");
112      }
113  
```
[Open in Flare](https://flareapp.io/errors/1495843/latest)

**Comment by colleenskemp** [comment]
Is the health check running while the views are being cached?
