### ISSUE TITLE
Community org page creation - groups you can connect to: Specific disability not saving

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#911]
The field "please select people with disabilities that you specifically serve and support" doesn't seem to be saving if I select "specific disability or disabilities".

**Comment by greatislander** [comment]
@jobara When you are working on this page for publishability can you check this? I think @chosww may have fixed it in his earlier PR.

**Comment by jobara** [comment]
> @jobara When you are working on this page for publishability can you check this? I think @chosww may have fixed it in his earlier PR.

I'm still seeing issues with the "old" value if there was another validation error on the page. Has @chosww's changes been merged?

**Comment by greatislander** [comment]
They have…
