### ISSUE TITLE
Individual page creation: checkbox randering issues while using on screen keybord

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#939]
Safari/ on screen keyboard / Individual page creation: 
As we were going through different steps of page creation, sometimes check boxes and radio buttons were not rendered properly. We had to use arrow keys to scroll up and down to fix the issue. A screen shot of one of these instances is attached. 

![Image](https://user-images.githubusercontent.com/10619898/186499647-841231d2-256d-4d1c-bfaf-2f4c1fc48a63.png)

**Comment by cherylhjli** [comment]
@sepidehshahi please recreate this

**Comment by sepidehshahi** [comment]
Tested on Safari and Chrome and couldn't reproduce the issue.

**Comment by greatislander** [comment]
I can't reproduce this either.
