### ISSUE TITLE
Account creation: add hide/show password icon to the password creation fields

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#943]

**Comment by cherylhjli** [comment]
Since it's a checkbox with the label "show password" (and checking it off doesn't change the text), we can use the hero icon "eye". See it in the wireframe here: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A4220
