### ISSUE TITLE
Add the contrast options to the top navigation, so user can adjust the contrast even without an account and while browsing home pages.

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#952]
Head tracker user had difficulty seeing the buttons in the default colour while creating an account. Once they created their account, they were not able to find the display preferences settings on their own. Having the contrast option up front will greatly help the navigation.

**Comment by cherylhjli** [comment]
Added the contrast button next to the language button: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A3399

menu expanded: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=4178%3A100560

mobile: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A3454

On mobile, we can use the same menu style for language for the contrast options as well.
