### ISSUE TITLE
Add a button to go back to the top

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#953]
This will help switch and head tracker users to easier navigate the page, particularly longer pages as scrolling is very difficult with these ATs.

**Comment by cherylhjli** [comment]
Borderless button with arrow-up icon, on a grey2 background that spans the width of the page, as seen on this page: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1806%3A53578
