### ISSUE TITLE
Home page: switch the placement of links and images. Have the links on the left and images on the right column.

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#954]
Since scanning happens from the left, having the links on the left makes navigation more efficient. This change will also support magnifier users and reduces the mouse movement for head tracker users.

**Comment by cherylhjli** [comment]
All text is on the left side now: https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=4%3A136

**Comment by greatislander** [comment]
Resolved in #1254.
