### ISSUE TITLE
Registration: Add terms of service and privacy policy checkboxes

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#975]
Add the checkboxes for terms of service and privacy policy to the password page in the registration flow.

**Comment by greatislander** [comment]
Blocked by absence of TOS and Privacy Policy.

**Comment by greatislander** [comment]
https://www.figma.com/file/AXufBnFAVHvGdsxnQMVhNF/The-Accessibility-Exchange-Wireframes?node-id=1125%3A4220

**Comment by greatislander** [comment]
The `User` model needs two new columns:

- `accepted_privacy_policy_at` (datetime)
- `accepted_terms_of_service_at` (datetime)

They need to be set to `now()` within `App\Actions\Fortify\CreateNewUser::create()`.
